### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by owencz1998** [toasterofbread/spmp#106]
java.io.FileNotFoundException: /data/user/0/com.toasterofbread.spmp/cache/spmp/feed_rows: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:574)
	at java.io.FileInputStream.<init>(FileInputStream.java:160)
	at com.toasterofbread.spmp.model.Cache$Companion.clean(Unknown Source:56)
	at com.toasterofbread.spmp.model.Cache$Companion$init$1.invoke(Unknown Source:2)
	at com.toasterofbread.spmp.model.Cache$Companion$init$1.invoke(Unknown Source:0)
	at androidx.media3.decoder.SimpleDecoder$1.run(Unknown Source:32)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8619)
	at libcore.io.IoBridge.open(IoBridge.java:560)
	... 5 more

Simply opened the app and this always shows.

**Comment by toasterofbread** [comment]
Will be fixed in the next release
