### ISSUE TITLE
[Bug] Crashes on first launch if system language is unsupported

### ISSUE THREAD

**Issue by szescxz** [toasterofbread/spmp#111]
**Describe the bug**
App launches with a blank screen.

**To Reproduce**
Steps to reproduce the behaviour:
1. Clear data of the app in system settings.
2. Launch the app with system language set to "Chinese (Simplified)".

A few things to note:
- It launches if set to "English (United States)".
- The crash is no longer observed if the in-app "Interface language" is set.

**Expected behaviour**
N/A

**Environment**
- OS name and version
MIUI 14 by xiaomi.eu, Android 12
- SpMp version
e406dd71103485c5e8ffe56e4e0c4c15ed120f36 (debug build downloaded from https://github.com/toasterofbread/spmp/actions/runs/5849900402)
- Accounts
N/A

**Screenshots**
N/A

**Logs**
```08-14 09:55:07.815 12022 12022 D AndroidRuntime: Shutting down VM
08-14 09:55:07.816 12022 12022 E AndroidRuntime: FATAL EXCEPTION: main
08-14 09:55:07.816 12022 12022 E AndroidRuntime: Process: com.toasterofbread.spmp.debug, PID: 12022
08-14 09:55:07.816 12022 12022 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.toasterofbread.spmp.debug/com.toasterofbread.spmp.MainActivity}: java.lang.ArrayIndexOutOfBoundsException: length=83; index=-1
08-14 09:55:07.816 12022 12022 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(Unknown Source:697)
08-14 09:55:07.816 12022 12022 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(Unknown Source:94)
08-14 09:55:07.816 12022 12022 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(Unknown Source:12)
08-14 09:55:07.816 12022 12022 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(Unknown Source:77)
08-14 09:55:07.816 12022 12022 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(Unknown Source:73)
08-14 09:55:07.816 12022 12022 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(Unknown Source:127)
08-14 09:55:07.816 12022 12022 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Unknown Source:19)
08-14 09:55:07.816 12022 12022 E AndroidRuntime: 	at android.os.Looper.loopOnce(Unknown Source:176)
08-14 09:55:07.816 12022 12022 E AndroidRuntime: 	at android.os.Looper.loop(Unknown Source:76)
08-14 09:55:07.816 12022 12022 E AndroidRuntime: 	at android.app.ActivityThread.main(Unknown Source:138)
08-14 09:55:07.816 12022 12022 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-14 09:55:07.816 12022 12022 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
08-14 09:55:07.816 12022 12022 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(Unknown Source:309)
08-14 09:55:07.816 12022 12022 E AndroidRuntime: Caused by: java.lang.ArrayIndexOutOfBoundsException: length=83; index=-1
08-14 09:55:07.816 12022 12022 E AndroidRuntime: 	at java.util.Arrays$ArrayList.get(Arrays.java:3766)
08-14 09:55:07.816 12022 12022 E AndroidRuntime: 	at SpMp.init(SpMp.kt:98)
08-14 09:55:07.816 12022 12022 E AndroidRuntime: 	at com.toasterofbread.spmp.MainActivity$onCreate$context$1.invoke(MainActivity.kt:53)
08-14 09:55:07.816 12022 12022 E AndroidRuntime: 	at com.toasterofbread.spmp.MainActivity$onCreate$context$1.invoke(MainActivity.kt:52)
08-14 09:55:07.816 12022 12022 E AndroidRuntime: 	at com.toasterofbread.spmp.platform.PlatformContext.<init>(PlatformContext.android.kt:59)
08-14 09:55:07.816 12022 12022 E AndroidRuntime: 	at com.toasterofbread.spmp.MainActivity.onCreate(MainActivity.kt:52)
08-14 09:55:07.816 12022 12022 E AndroidRuntime: 	at android.app.Activity.performCreate(Unknown Source:125)
08-14 09:55:07.816 12022 12022 E AndroidRuntime: 	at android.app.Activity.performCreate(Unknown Source:1)
08-14 09:55:07.816 12022 12022 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Unknown Source:3)
08-14 09:55:07.816 12022 12022 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(Unknown Source:433)
08-14 09:55:07.816 12022 12022 E AndroidRuntime: 	... 12 more
```
https://github.com/toasterofbread/spmp/blob/e406dd71103485c5e8ffe56e4e0c4c15ed120f36/shared/src/commonMain/kotlin/SpMp.kt#L98

**Comment by toasterofbread** [comment]
Thanks! Should be fixed in main.
