### ISSUE TITLE
[Bug] Crash while main page was loading

### ISSUE THREAD

**Issue by opusforlife2** [toasterofbread/spmp#114]
**Describe the bug**

Opened the app and the feed was loading. The crash occurred without any user input. The UI stopped responding to taps until the app was removed from Recents and then reopened.

**Environment**
- Android 13
- SpMp version: v0.1.4

**Logs**

Your error page is really nice, BTW. Clean and easy to use.

```
kotlin.NotImplementedError: MUSIC_PAGE_TYPE_ARTIST_DISCOGRAPHY
	at com.toasterofbread.spmp.model.mediaitem.MediaItem$Companion.fromBrowseEndpointType(Unknown Source:88)
	at com.toasterofbread.spmp.api.BrowseEndpoint.getMediaItem(Unknown Source:10)
	at com.toasterofbread.spmp.api.BrowseEndpoint.getViewMore(Unknown Source:2)
	at com.toasterofbread.spmp.api.NavigationEndpoint.getViewMore(Unknown Source:4)
	at com.toasterofbread.spmp.api.LoadMediaitemKt$processDefaultResponse$2.invokeSuspend(Unknown Source:1194)
	at com.toasterofbread.spmp.api.LoadMediaitemKt$processDefaultResponse$2.invoke(Unknown Source:8)
	at com.toasterofbread.spmp.api.LoadMediaitemKt$processDefaultResponse$2.invoke(Unknown Source:4)
	at androidx.core.R$dimen.startUndispatchedOrReturn(Unknown Source:4)
	at coil.util.-Contexts.withContext(Unknown Source:71)
	at com.toasterofbread.spmp.api.LoadMediaitemKt.processDefaultResponse(Unknown Source:13)
	at com.toasterofbread.spmp.api.LoadMediaitemKt$loadMediaItemData$2.invokeSuspend(Unknown Source:241)
	at com.toasterofbread.spmp.api.LoadMediaitemKt$loadMediaItemData$2.invoke(Unknown Source:8)
	at com.toasterofbread.spmp.api.LoadMediaitemKt$loadMediaItemData$2.invoke(Unknown Source:4)
	at androidx.core.R$dimen.startUndispatchedOrReturn(Unknown Source:4)
	at coil.util.-Contexts.withContext(Unknown Source:71)
	at com.toasterofbread.spmp.api.LoadMediaitemKt.loadMediaItemData(Unknown Source:76)
	at com.toasterofbread.spmp.model.mediaitem.MediaItem$loadGeneralData$2.invokeSuspend(Unknown Source:121)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:100)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(Unknown Source:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:79)
	Suppressed: coil.network.HttpException: [androidx.compose.ui.platform.MotionDurationScaleImpl@ff90c68, androidx.compose.runtime.BroadcastFrameClock@f422881, StandaloneCoroutine{Cancelling}@c48bd26, AndroidUiDispatcher@5fe4d67]
```

**Comment by toasterofbread** [comment]
> BTW, it would be nice of you to credit Newpipe Extractor in your ReadMe along with the other projects. 👀

Good idea, not sure why I'm not doing this already.

**Comment by toasterofbread** [comment]
> BTW, it would be nice of you to credit Newpipe Extractor in your ReadMe along with the other projects. 👀

[Added!](https://github.com/toasterofbread/spmp/commit/85683fa79e1b0a1b67166c3de9546650c360ecaa)
