### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by donmega** [toasterofbread/spmp#132]
**Describe the bug**

After logging on using the newest beta, i get the following error:

java.util.zip.ZipException: Not in GZIP format
	at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:174)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:83)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:100)
	at com.toasterofbread.spmp.youtubeapi.impl.youtubemusic.YoutubeMusicApi.getResponseStream(Unknown Source:20)
	at com.toasterofbread.spmp.youtubeapi.YoutubeApiKt.getStream(Unknown Source:7)
	at com.toasterofbread.spmp.youtubeapi.impl.youtubemusic.endpoint.YTMYoutubeChannelCreationFormEndpoint$getForm$2.invokeSuspend(Unknown Source:96)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:100)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(Unknown Source:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:79)
	Suppressed: coil.network.HttpException: [androidx.compose.ui.platform.MotionDurationScaleImpl@34159e0, androidx.compose.runtime.BroadcastFrameClock@f75b499, StandaloneCoroutine{Cancelling}@97ab35e, AndroidUiDispatcher@499333f]

**Steps To Reproduce**

1. Press the login button
2. Enter my username and password
3. Error appears

**Expected behaviour**

**Environment**
- Android 11
- SpMp version: 0.1.3 (beta of 1 week ago)

**Screenshots**

**Logs**

When using the official release, it hangs after logging in.

Thank you for your time!

**Comment by toasterofbread** [comment]
Thanks! Should be fixed.
