### ISSUE TITLE
When i open the app it shows error and then the home screen doesnt respond to anything, even after clicking on any song or something it doesnt respond

### ISSUE THREAD

**Issue by dainvincible1** [toasterofbread/spmp#140]
https://github.com/toasterofbread/spmp/assets/127825700/789df668-e49a-4c62-9db4-d58e148e393f

**Comment by zerobun** [comment]
It's happening me too, just came here to report it but yes.

Im getting this error:
```kotlin
kotlin.NotImplementedError: MUSIC_PAGE_TYPE_NON_MUSIC_AUDIO_TRACK_PAGE (MPEDEjwEzMZSFfg)
	at com.toasterofbread.spmp.youtubeapi.model.MusicTwoRowItemRenderer.toMediaItem(Unknown Source:249)
	at com.toasterofbread.spmp.youtubeapi.model.YoutubeiShelfContentsItem.toMediaItemData(Unknown Source:10)
	at com.toasterofbread.spmp.youtubeapi.model.YoutubeiShelf.getMediaItemsAndSetIds(Unknown Source:72)
	at com.toasterofbread.spmp.youtubeapi.impl.youtubemusic.LoadMediaitemKt$processDefaultResponse$2.invokeSuspend(Unknown Source:1026)
	at com.toasterofbread.spmp.youtubeapi.impl.youtubemusic.LoadMediaitemKt$processDefaultResponse$2.invoke(SourceFile:2)
	at com.toasterofbread.spmp.youtubeapi.impl.youtubemusic.LoadMediaitemKt$processDefaultResponse$2.invoke(SourceFile:1)
	at coil.util.-Lifecycles.startUndispatchedOrReturn(Unknown Source:4)
	at okio.Okio.withContext(Unknown Source:71)
	at com.toasterofbread.spmp.youtubeapi.impl.youtubemusic.LoadMediaitemKt.processDefaultResponse(Unknown Source:65)
	at com.toasterofbread.spmp.youtubeapi.impl.youtubemusic.endpoint.YTMLoadArtistEndpoint$loadArtist$2.invokeSuspend(Unknown Source:155)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:102)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(Unknown Source:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:76)
	Suppressed: coil.network.HttpException: [androidx.compose.ui.platform.MotionDurationScaleImpl@cebce0, androidx.compose.runtime.BroadcastFrameClock@ad2db99, StandaloneCoroutine{Cancelling}@c064e5e, AndroidUiDispatcher@544323f]

```

**Comment by zerobun** [comment]
I tried using the universal v7 and v8 too for the apk, same result it seems.
