### ISSUE TITLE
[Bug] Crash caused by TransactionTooLargeException

### ISSUE THREAD

**Issue by rahulzprofilez** [toasterofbread/spmp#154]
kotlin.NotImplementedError: Fatal exception in coroutines machinery for AwaitContinuation(DispatchedContinuation[AndroidUiDispatcher@88dc2ea, Continuation at com.toasterofbread.spmp.model.mediaitem.loader.Loader$LoadJob.await(Loader.kt:126)@aa4cf51]){Completed}@8fd23b6. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
	at kotlinx.coroutines.DispatchedTask.handleFatalException(Unknown Source:39)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:159)
	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(Unknown Source:22)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:978)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loopOnce(Looper.java:238)
	at android.os.Looper.loop(Looper.java:357)
	at android.app.ActivityThread.main(ActivityThread.java:8090)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
	Suppressed: coil.network.HttpException: [androidx.compose.ui.platform.MotionDurationScaleImpl@3c490bf, androidx.compose.runtime.BroadcastFrameClock@186038c, ScopeCoroutine{Cancelled}@8160f8d, AndroidUiDispatcher@88dc2ea]
Caused by: java.lang.RuntimeException: Failure from system
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1814)
	at android.app.Activity.startActivityForResult(Activity.java:5506)
	at androidx.activity.ComponentActivity.startActivityForResult(SourceFile:2)
	at android.app.Activity.startActivityForResult(Activity.java:5464)
	at androidx.activity.ComponentActivity.startActivityForResult(SourceFile:1)
	at android.app.Activity.startActivity(Activity.java:5854)
	at android.app.Activity.startActivity(Activity.java:5807)
	at com.toasterofbread.spmp.MainActivity.onCreate$lambda$1(Unknown Source:68)
	at com.toasterofbread.spmp.MainActivity.$r8$lambda$W9P82hyiZbMh8Pba-p9uZk-2Ue4(Unknown Source:0)
	at com.toasterofbread.spmp.MainActivity$$ExternalSyntheticLambda0.uncaughtException(Unknown Source:2)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
	at kotlinx.coroutines.CoroutineExceptionHandlerImplKt.handleCoroutineExceptionImpl(Unknown Source:70)
	at coil.util.-FileSystems.handleCoroutineException(Unknown Source:14)
	at kotlinx.coroutines.StandaloneCoroutine.handleJobException(Unknown Source:2)
	at kotlinx.coroutines.JobSupport.finalizeFinishingState(Unknown Source:105)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(Unknown Source:222)
	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(Unknown Source:4)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(Unknown Source:13)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:31)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Unknown Source:6)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(Unknown Source:22)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:31)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:102)
	... 10 more
Caused by: android.os.TransactionTooLargeException: data parcel size 2885472 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:571)
	at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:2371)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1808)
	... 33 more

**Comment by toasterofbread** [comment]
Please provide information about how/when the error occurred, don't just upload the stack trace. When did it occur? Is it consistent?

Could you also provide the version/commit you're using as well as the name and version of your OS and whether you were signed in to YouTube/Discord when this happened?

**Comment by toasterofbread** [comment]
If you're able to reproduce this, please upload the logs surrounding the crash using logcat or an app like [this one](https://play.google.com/store/apps/details?id=com.conena.logcat.reader&hl=en_US).
