### ISSUE TITLE
[Bug] Database migration not working, leads to SQLiteException (no such column)

### ISSUE THREAD

**Issue by Urbexed** [toasterofbread/spmp#161]
I open it and I get this message. 

android.database.sqlite.SQLiteException: no such column: title_data (code 1 SQLITE_ERROR): , while compiling: UPDATE ArtistLayout SET title_data = ? WHERE artist_id == ? AND layout_index = ?
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1068)
	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:673)
	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:62)
	at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:34)
	at android.database.sqlite.SQLiteDatabase.compileStatement(SQLiteDatabase.java:1390)
	at ErrorManager$Indicator$6$2$4.invoke(SourceFile:22)
	at app.cash.sqldelight.driver.android.AndroidSqliteDriver.execute-zeHU3Mk(Unknown Source:14)
	at app.cash.sqldelight.driver.android.AndroidSqliteDriver.execute(Unknown Source:14)
	at com.toasterofbread.spmp.model.mediaitem.artist.ArtistLayout$Title$3.invoke(SourceFile:2)
	at com.toasterofbread.spmp.model.mediaitem.artist.ArtistLayout$Title$3.invoke(SourceFile:1)
	at com.toasterofbread.spmp.model.mediaitem.db.PropertyImpl.set(Unknown Source:7)
	at com.toasterofbread.spmp.model.mediaitem.db.Property$DefaultImpls.setNotNull(Unknown Source:13)
	at com.toasterofbread.spmp.model.mediaitem.db.PropertyImpl.setNotNull(Unknown Source:0)
	at com.toasterofbread.spmp.model.mediaitem.db.Property$DefaultImpls.setNotNull$default(Unknown Source:7)
	at com.toasterofbread.spmp.model.mediaitem.artist.ArtistLayoutData$saveToDatabase$1.invoke(SourceFile:2)
	at com.toasterofbread.spmp.model.mediaitem.artist.ArtistLayoutData$saveToDatabase$1.invoke(SourceFile:1)
	at app.cash.sqldelight.TransacterImpl.transactionWithWrapper(Unknown Source:52)
	at io.grpc.Contexts.transaction$default(Unknown Source:6)
	at com.toasterofbread.spmp.model.mediaitem.artist.ArtistLayoutData.saveToDatabase(Unknown Source:10)
	at com.toasterofbread.spmp.model.mediaitem.artist.ArtistData$saveToDatabase$1.invoke(SourceFile:2)
	at com.toasterofbread.spmp.model.mediaitem.artist.ArtistData$saveToDatabase$1.invoke(SourceFile:1)
	at app.cash.sqldelight.TransacterImpl.transactionWithWrapper(Unknown Source:52)
	at io.grpc.Contexts.transaction$default(Unknown Source:6)
	at com.toasterofbread.spmp.model.mediaitem.artist.ArtistData.saveToDatabase(Unknown Source:15)
	at com.toasterofbread.spmp.model.mediaitem.MediaItemData.saveToDatabase$default(Unknown Source:12)
	at com.toasterofbread.spmp.youtubeapi.impl.youtubemusic.endpoint.YTMLoadArtistEndpoint$loadArtist$2.invokeSuspend(Unknown Source:234)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:102)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(Unknown Source:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:76)
	Suppressed: coil.network.HttpException: [androidx.compose.ui.platform.MotionDurationScaleImpl@4a1d5cb, androidx.compose.runtime.BroadcastFrameClock@e0e11a8, StandaloneCoroutine{Cancelling}@54ee4c1, AndroidUiDispatcher@a906466]

And then I can't do anything at all

**Comment by Urbexed** [comment]
Edit : I uninstalled the app. I tried deleting all the data and it worked but then I couldn't reconnect to discord 

If it's to fight to use the application I prefer to give up
