### ISSUE TITLE
Can't log in (was able to log in previously)

### ISSUE THREAD

**Issue by David41413** [toasterofbread/spmp#191]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/toasterofbread/spmp/actions/workflows/android.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

1. Press the login button
2. Enter username and password
3. Error appears

### Expected behavior

Log in successfully

### Actual behavior

Met with error

### Logs

android.os.NetworkOnMainThreadException
	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1667)
	at com.android.org.conscrypt.Platform.blockGuardOnNetwork(Platform.java:432)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:836)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:824)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:797)
	at okio.InputStreamSource.read(SourceFile:56)
	at okio.InputStreamSource.read(SourceFile:133)
	at okio.RealBufferedSource.exhausted(Unknown Source:18)
	at okhttp3.internal.connection.RealConnection.isHealthy(SourceFile:81)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(SourceFile:326)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(SourceFile:60)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:135)
	at okhttp3.internal.cache.CacheInterceptor.intercept(SourceFile:122)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:135)
	at okhttp3.internal.http.BridgeInterceptor.intercept(SourceFile:141)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:135)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(SourceFile:148)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:135)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(SourceFile:96)
	at okhttp3.internal.connection.RealCall.execute(SourceFile:44)
	at com.toasterofbread.spmp.youtubeapi.YoutubeApiKt.executeResult(SourceFile:15)
	at com.toasterofbread.spmp.youtubeapi.impl.youtubemusic.YoutubeMusicApi.performRequest-0E7RQCE(Unknown Source:12)
	at com.toasterofbread.spmp.youtubeapi.YoutubeApi$DefaultImpls.performRequest-0E7RQCE$default(Unknown Source:12)
	at com.toasterofbread.spmp.youtubeapi.impl.youtubemusic.composable.YTMLoginPage.completeLogin-gIAlu-s(SourceFile:119)
	at com.toasterofbread.spmp.youtubeapi.impl.youtubemusic.composable.YTMLoginPage.access$completeLogin-gIAlu-s(Unknown Source:0)
	at com.toasterofbread.spmp.youtubeapi.impl.youtubemusic.composable.YTMLoginPage$LoginPage$3$5$1$1.invokeSuspend(SourceFile:39)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:107)
	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(SourceFile:7)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(SourceFile:3)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

### SpMp version

0.2.3

### Android version

Android 13

### Additional information

I tried downloading SPMP on another phone but I couldn't log in.

**Comment by toasterofbread** [comment]
> I am able to reproduce the bug with the latest debug version

Which build did you try? This should've been fixed a while ago.

**Comment by David41413** [comment]
> > I am able to reproduce the bug with the latest debug version
> 
> Which build did you try? This should've been fixed a while ago.

I'm using the universal release version, if that's what you mean.

**Comment by toasterofbread** [comment]
This bug was fixed in bf635b7dcb91ea3b778318de5c52eceed7ead8cb (it was only mentioned in a [comment](https://github.com/toasterofbread/spmp/issues/176#issuecomment-1774038852) on an unrelated issue and didn't have its own issue). 

Please don't mark the 'I am able to reproduce the bug with the latest debug version' if you haven't tested this with the latest [debug version](https://github.com/toasterofbread/spmp/actions/workflows/android.yml).
