### ISSUE TITLE
Crashing when I try to download something

### ISSUE THREAD

**Issue by XxRiKxX** [toasterofbread/spmp#214]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/toasterofbread/spmp/actions/workflows/android.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

Click on a song.
Click on the download button from menu.
It will ask for notifications permissions.
Allow it and it crashes.
Don't allow it and it don't downloads.

### Expected behavior

Download the music

### Actual behavior

Freezes and then crashes

### Logs

Where is it stored?

### SpMp version

0.2.4

### Android version

14

### Additional information

Tried with piped API too same result. The app was perfectly fine on lineage os android 13. I am now on evolution x android 14 and experiencing this bug

**Comment by toasterofbread** [comment]
Please provide the logs associated with the crash using Logcat, a similar tool, or by [capturing a bug report](https://developer.android.com/studio/debug/bug-report). Was there no stacktrace displayed when the app crashed?

**Comment by Armaldio** [comment]
Can you please reopen ?

Here is the logcat:
```
2024-02-19 12:52:06.613 15448-15448 AndroidRuntime          com.toasterofbread.spmp              E  FATAL EXCEPTION: main
                                                                                                    Process: com.toasterofbread.spmp, PID: 15448
                                                                                                    android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{374482e 15448:com.toasterofbread.spmp/u0a795} targetSDK=34
                                                                                                    	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:53)
                                                                                                    	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:49)
                                                                                                    	at android.os.Parcel.readParcelableInternal(Parcel.java:5015)
                                                                                                    	at android.os.Parcel.readParcelable(Parcel.java:4997)
                                                                                                    	at android.os.Parcel.createExceptionOrNull(Parcel.java:3177)
                                                                                                    	at android.os.Parcel.createException(Parcel.java:3166)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:3149)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:3091)
                                                                                                    	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6912)
                                                                                                    	at android.app.Service.startForeground(Service.java:775)
                                                                                                    	at com.toasterofbread.spmp.PlayerDownloadService.startDownload(SourceFile:183)
                                                                                                    	at com.toasterofbread.spmp.PlayerDownloadService.onActionIntentReceived(SourceFile:44)
                                                                                                    	at com.toasterofbread.spmp.PlayerDownloadService.onMessage(Unknown Source:6)
                                                                                                    	at com.toasterofbread.spmp.platform.PlayerDownloadManager$performDownload$1.invoke(SourceFile:5)
                                                                                                    	at com.toasterofbread.spmp.platform.PlayerDownloadManager$performDownload$1.invoke(SourceFile:1)
                                                                                                    	at com.toasterofbread.spmp.platform.PlayerDownloadManager$onService$2.invoke(SourceFile:2)
                                                                                                    	at com.toasterofbread.spmp.platform.PlayerDownloadManager$onService$2.invoke(SourceFile:1)
                                                                                                    	at com.toasterofbread.spmp.platform.PlayerDownloadManager$startService$2.invoke(SourceFile:2)
                                                                                                    	at com.toasterofbread.spmp.platform.PlayerDownloadManager$startService$2.invoke(SourceFile:1)
                                                                                                    	at com.toasterofbread.spmp.platform.PlatformService_androidKt$startPlatformService$service_connection$1.onServiceConnected(Unknown Source:11)
                                                                                                    	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2206)
                                                                                                    	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2239)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:959)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                    	at android.os.Looper.loop(Looper.java:317)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8516)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
2024-02-19 12:52:06.613 15448-15448 System.err              com.toasterofbread.spmp              W  android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{374482e 15448:com.toasterofbread.spmp/u0a795} targetSDK=34
2024-02-19 12:52:06.613 15448-15448 System.err              com.toasterofbread.spmp              W  	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:53)
2024-02-19 12:52:06.613 15448-15448 System.err              com.toasterofbread.spmp              W  	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:49)
2024-02-19 12:52:06.613 15448-15448 System.err              com.toasterofbread.spmp              W  	at android.os.Parcel.readParcelableInternal(Parcel.java:5015)
2024-02-19 12:52:06.613 15448-15448 System.err              com.toasterofbread.spmp              W  	at android.os.Parcel.readParcelable(Parcel.java:4997)
2024-02-19 12:52:06.613 15448-15448 System.err              com.toasterofbread.spmp              W  	at android.os.Parcel.createExceptionOrNull(Parcel.java:3177)
2024-02-19 12:52:06.613 15448-15448 System.err              com.toasterofbread.spmp              W  	at android.os.Parcel.createException(Parcel.java:3166)
2024-02-19 12:52:06.614 15448-15448 System.err              com.toasterofbread.spmp              W  	at android.os.Parcel.readException(Parcel.java:3149)
2024-02-19 12:52:06.614 15448-15448 System.err              com.toasterofbread.spmp              W  	at android.os.Parcel.readException(Parcel.java:3091)
2024-02-19 12:52:06.614 15448-15448 System.err              com.toasterofbread.spmp              W  	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6912)
2024-02-19 12:52:06.614 15448-15448 System.err              com.toasterofbread.spmp              W  	at android.app.Service.startForeground(Service.java:775)
2024-02-19 12:52:06.614 15448-15448 System.err              com.toasterofbread.spmp              W  	at com.toasterofbread.spmp.PlayerDownloadService.startDownload(SourceFile:183)
2024-02-19 12:52:06.614 15448-15448 System.err              com.toasterofbread.spmp              W  	at com.toasterofbread.spmp.PlayerDownloadService.onActionIntentReceived(SourceFile:44)
2024-02-19 12:52:06.614 15448-15448 System.err              com.toasterofbread.spmp              W  	at com.toasterofbread.spmp.PlayerDownloadService.onMessage(Unknown Source:6)
2024-02-19 12:52:06.614 15448-15448 System.err              com.toasterofbread.spmp              W  	at com.toasterofbread.spmp.platform.PlayerDownloadManager$performDownload$1.invoke(SourceFile:5)
2024-02-19 12:52:06.614 15448-15448 System.err              com.toasterofbread.spmp              W  	at com.toasterofbread.spmp.platform.PlayerDownloadManager$performDownload$1.invoke(SourceFile:1)
2024-02-19 12:52:06.614 15448-15448 System.err              com.toasterofbread.spmp              W  	at com.toasterofbread.spmp.platform.PlayerDownloadManager$onService$2.invoke(SourceFile:2)
2024-02-19 12:52:06.614 15448-15448 System.err              com.toasterofbread.spmp              W  	at com.toasterofbread.spmp.platform.PlayerDownloadManager$onService$2.invoke(SourceFile:1)
2024-02-19 12:52:06.614 15448-15448 System.err              com.toasterofbread.spmp              W  	at com.toasterofbread.spmp.platform.PlayerDownloadManager$startService$2.invoke(SourceFile:2)
2024-02-19 12:52:06.614 15448-15448 System.err              com.toasterofbread.spmp              W  	at com.toasterofbread.spmp.platform.PlayerDownloadManager$startService$2.invoke(SourceFile:1)
2024-02-19 12:52:06.614 15448-15448 System.err              com.toasterofbread.spmp              W  	at com.toasterofbread.spmp.platform.PlatformService_androidKt$startPlatformService$service_connection$1.onServiceConnected(Unknown Source:11)
2024-02-19 12:52:06.614 15448-15448 System.err              com.toasterofbread.spmp              W  	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2206)
2024-02-19 12:52:06.614 15448-15448 System.err              com.toasterofbread.spmp              W  	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2239)
2024-02-19 12:52:06.614 15448-15448 System.err              com.toasterofbread.spmp              W  	at android.os.Handler.handleCallback(Handler.java:959)
2024-02-19 12:52:06.614 15448-15448 System.err              com.toasterofbread.spmp              W  	at android.os.Handler.dispatchMessage(Handler.java:100)
2024-02-19 12:52:06.614 15448-15448 System.err              com.toasterofbread.spmp              W  	at android.os.Looper.loopOnce(Looper.java:232)
2024-02-19 12:52:06.614 15448-15448 System.err              com.toasterofbread.spmp              W  	at android.os.Looper.loop(Looper.java:317)
2024-02-19 12:52:06.614 15448-15448 System.err              com.toasterofbread.spmp              W  	at android.app.ActivityThread.main(ActivityThread.java:8516)
2024-02-19 12:52:06.614 15448-15448 System.err              com.toasterofbread.spmp              W  	at java.lang.reflect.Method.invoke(Native Method)
2024-02-19 12:52:06.614 15448-15448 System.err              com.toasterofbread.spmp              W  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
2024-02-19 12:52:06.614 15448-15448 System.err              com.toasterofbread.spmp              W  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
2024-02-19 12:52:12.162 15448-15456 terofbread.spmp         com.toasterofbread.spmp              I  Thread[6,tid=15456,WaitingInMainSignalCatcherLoop,Thread*=0xb400007120418f50,peer=0x12c01710,"Signal Catcher"]: reacting to signal 3
2024-02-19 12:52:12.162 15448-15456 terofbread.spmp         com.toasterofbread.spmp              I  
2024-02-19 12:52:12.316 15448-15456 terofbread.spmp         com.toasterofbread.spmp              I  Wrote stack traces to tombstoned

```

There are no stack trace displayed (as opposed to other errors)

Running Android 14 on Pixel 7 pro

**Comment by toasterofbread** [comment]
@Armaldio Have you tried with a [nightly build](https://nightly.link/toasterofbread/spmp/workflows/build-android/main)? I think this may have been fixed recently.

**Comment by Armaldio** [comment]
Indeed, that works fine. I missed that I could get debug build
When can we expect a release ?

**Comment by toasterofbread** [comment]
I'm aiming to make a new release in the next couple of days.
