### ISSUE TITLE
Crash when viewing an account playlist with a song from youtube music's "upload music" feature

### ISSUE THREAD

**Issue by Fern-Leaves** [toasterofbread/spmp#226]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/toasterofbread/spmp/actions/workflows/android.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

1. Open app
2. Go to playlists section
3. Tap on an account playlist with 1 or more song from "upload music" in it
4. It will begin to load but crash before you can see any songs

### Expected behavior

the playlist will be able to be viewed and played without causing a crash

### Actual behavior

the app crashes before you can see a single song load in the playlist

### Screenshots / recordings

A recording of me causing this crash:
https://github.com/toasterofbread/spmp/assets/56755065/8009a725-b59f-4f27-a4f9-2896f87b5911

the "upload music" feature in question and a the song in question from it:
![image](https://github.com/toasterofbread/spmp/assets/56755065/24c1fa49-405d-4f2b-af54-2d0b7179b086)

### Logs

---STACK TRACE---
kotlin.NotImplementedError: MUSIC_PAGE_TYPE_UNKNOWN
    at com.toasterofbread.spmp.model.mediaitem.enums.MediaItemType$Companion.fromBrowseEndpointType(SourceFile:110)
    at com.toasterofbread.spmp.youtubeapi.model.BrowseEndpoint.getMediaItemType(Unknown Source:8)
    at com.toasterofbread.spmp.youtubeapi.model.MusicResponsiveListItemRenderer.toMediaItemAndPlaylistSetVideoId(SourceFile:273)
    at com.toasterofbread.spmp.youtubeapi.model.YoutubeiShelfContentsItem.toMediaItemData(Unknown Source:27)
    at com.toasterofbread.spmp.youtubeapi.model.YoutubeiShelf.getMediaItemsAndSetIds(Unknown Source:72)
    at com.toasterofbread.spmp.youtubeapi.impl.youtubemusic.LoadMediaitemKt$processDefaultResponse$2.invokeSuspend(SourceFile:1037)
    at com.toasterofbread.spmp.youtubeapi.impl.youtubemusic.LoadMediaitemKt$processDefaultResponse$2.invoke(SourceFile:2)
    at com.toasterofbread.spmp.youtubeapi.impl.youtubemusic.LoadMediaitemKt$processDefaultResponse$2.invoke(SourceFile:1)
    at okio.Okio__OkioKt.startUndispatchedOrReturn(SourceFile:5)
    at okio._UtilKt.withContext(SourceFile:75)
    at com.toasterofbread.spmp.youtubeapi.impl.youtubemusic.LoadMediaitemKt.processDefaultResponse(SourceFile:66)
    at com.toasterofbread.spmp.youtubeapi.impl.youtubemusic.endpoint.YTMLoadPlaylistEndpoint$loadPlaylist$2.invokeSuspend(SourceFile:704)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
    at kotlinx.coroutines.DispatchedTask.run(Unknown Source:107)
    at androidx.fragment.app.Fragment$4.run(SourceFile:105)
    at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:94)
    Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@f750e2c, androidx.compose.runtime.BroadcastFrameClock@130a0f5, StandaloneCoroutine{Cancelling}@53d5e8a, AndroidUiDispatcher@6ab7cfb]
---LOGCAT (last 119 lines)---
02-05 20:49:19.030  9976 10027 I System.out: Playing song IHQH57y2d7Y from local file PlatformFile(uri=/data/user/0/com.toasterofbread.spmp/files/library/songs/IHQH57y2d7Y.webm, file=/data/user/0/com.toasterofbread.spmp/files/library/songs/IHQH57y2d7Y.webm, parent_file=null)
02-05 20:49:19.056  9976 10016 I DMCodecAdapterFactory: Creating an asynchronous MediaCodec adapter for track type audio
02-05 20:49:19.058  9976 10029 D CCodec  : allocate(c2.android.opus.decoder)
02-05 20:49:19.060  9976 10029 I Codec2Client: Available Codec2 services: "default" "default1" "default2" "software"
02-05 20:49:19.061  9976 10029 I CCodec  : setting up 'default' as default (vendor) store
02-05 20:49:19.067  9976 10009 D TrafficStats: tagSocket(116) with statsTag=0xffffffff, statsUid=-1
02-05 20:49:19.073  9976  9976 D CompatibilityChangeReporter: Compat change id reported: 171228096; UID 10457; state: ENABLED
02-05 20:49:19.074  9976 10029 I CCodec  : Created component [c2.android.opus.decoder]
02-05 20:49:19.074  9976 10029 D CCodecConfig: read media type: audio/opus
02-05 20:49:19.076  9976 10029 D ReflectedParamUpdater: extent() != 1 for single value type: algo.buffers.max-count.values
02-05 20:49:19.076  9976 10029 D ReflectedParamUpdater: extent() != 1 for single value type: output.subscribed-indices.values
02-05 20:49:19.076  9976 10029 D ReflectedParamUpdater: extent() != 1 for single value type: input.buffers.allocator-ids.values
02-05 20:49:19.076  9976 10029 D ReflectedParamUpdater: extent() != 1 for single value type: output.buffers.allocator-ids.values
02-05 20:49:19.076  9976 10029 D ReflectedParamUpdater: extent() != 1 for single value type: algo.buffers.allocator-ids.values
02-05 20:49:19.076  9976 10029 D ReflectedParamUpdater: extent() != 1 for single value type: output.buffers.pool-ids.values
02-05 20:49:19.076  9976 10029 D ReflectedParamUpdater: extent() != 1 for single value type: algo.buffers.pool-ids.values
02-05 20:49:19.077  9976 10029 I CCodecConfig: query failed after returning 7 values (BAD_INDEX)
02-05 20:49:19.077  9976 10029 D CCodecConfig: c2 config diff is Dict {
02-05 20:49:19.077  9976 10029 D CCodecConfig:   c2::u32 coded.bitrate.value = 6000
02-05 20:49:19.077  9976 10029 D CCodecConfig:   c2::u32 input.buffers.max-size.value = 5760
02-05 20:49:19.077  9976 10029 D CCodecConfig:   c2::u32 input.delay.value = 0
02-05 20:49:19.077  9976 10029 D CCodecConfig:   string input.media-type.value = "audio/opus"
02-05 20:49:19.077  9976 10029 D CCodecConfig:   string out

### SpMp version

0.2.4

### Android version

Android 14

### Additional information

I'm not using the "latest debug version" because I cannot find it, that link links to nothing.

**Comment by toasterofbread** [comment]
Sorry about the broken link, that should be fixed now.

This is a semi-duplicate of #211, which was fixed in eaef6ed. A new release should be out in the next few days, or you can try a [nightly build](https://github.com/toasterofbread/spmp/actions) in the meantime.
