### ISSUE TITLE
Crash when pressing the plus button in a playlist's menu

### ISSUE THREAD

**Issue by Fern-Leaves** [toasterofbread/spmp#236]
### Checklist

- [X] I am able to reproduce the bug with the latest debug version ([Android](https://nightly.link/toasterofbread/spmp/workflows/build-android/main), [Linux](https://nightly.link/toasterofbread/spmp/workflows/build-linux/main), [Windows](https://nightly.link/toasterofbread/spmp/workflows/build-windows/main))
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

1. Open the app
2. Go to the account section
3. Open any playlist
4. Press the + button
5. Crash

### Expected behavior

I don't know, I don't know what exactly that button is supposed to do but I don't think it is supposed to crash the app

### Actual behavior

crash

### Screenshots / recordings

https://github.com/toasterofbread/spmp/assets/56755065/6eb5d553-c93f-4106-ac32-0e95111694af

### Logs

<details>

---STACK TRACE---
kotlin.NotImplementedError: An operation is not implemented.
	at com.toasterofbread.spmp.ui.layout.playlistpage.PlaylistInteractionBarKt$PlaylistInteractionBar$1$2$1$3$1$1$2$2$1.invoke(PlaylistInteractionBar.kt:114)
	at com.toasterofbread.spmp.ui.layout.playlistpage.PlaylistInteractionBarKt$PlaylistInteractionBar$1$2$1$3$1$1$2$2$1.invoke(PlaylistInteractionBar.kt:112)
	at androidx.compose.foundation.ClickablePointerInputNode$pointerInput$3.invoke-k-4lQ0M(Clickable.kt:895)
	at androidx.compose.foundation.ClickablePointerInputNode$pointerInput$3.invoke(Clickable.kt:889)
	at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1.invokeSuspend(TapGestureDetector.kt:255)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:179)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:168)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:474)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:508)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:497)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:368)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl$PointerEventHandlerCoroutine.offerPointerEvent(SuspendingPointerInputFilter.kt:665)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.dispatchPointerEvent(SuspendingPointerInputFilter.kt:544)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.onPointerEvent-H0pRuoY(SuspendingPointerInputFilter.kt:566)
	at androidx.compose.foundation.AbstractClickablePointerInputNode.onPointerEvent-H0pRuoY(Clickable.kt:855)
	at androidx.compose.foundation.AbstractClickableNode.onPointerEvent-H0pRuoY(Clickable.kt:703)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:317)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:303)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:303)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:303)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:303)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:303)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:303)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:303)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:303)
	at androidx.compose.ui.input.pointer.NodeParent.dispatchMainEventPass(HitPathTracker.kt:183)
	at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(HitPathTracker.kt:102)
	at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-BIzXfog(PointerInputEventProcessor.kt:96)
	at androidx.compose.ui.platform.AndroidComposeView.sendMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1446)
	at androidx.compose.ui.platform.AndroidComposeView.handleMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1398)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(AndroidComposeView.android.kt:1338)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3123)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2804)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3123)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2804)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3123)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2804)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3123)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2804)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:490)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1904)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4403)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:448)
	at android.view.View.dispatchPointerEvent(View.java:15928)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7242)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7032)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6435)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6492)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6458)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6623)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6466)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6680)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6439)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6492)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6458)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6466)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6439)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9432)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9383)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9352)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9558)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:267)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loopOnce(Looper.java:162)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8248)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@57c5da0, androidx.compose.runtime.BroadcastFrameClock@43acd59, StandaloneCoroutine{Cancelling}@370bd1e, AndroidUiDispatcher@3d3d9ff]

---LOGCAT (last 173 lines)---
02-19 21:13:28.385  9242  9242 I ImeTracker: com.toasterofbread.spmp.debug:77afbcd9: onShown
02-19 21:13:35.255  9242  9242 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=ImeCallback=ImeOnBackInvokedCallback@142718725 Callback=android.window.IOnBackInvokedCallback$Stub$Proxy@3e1fb45
02-19 21:13:35.573  9242  9242 I ImeTracker: com.toasterofbread.spmp.debug:efd97061: onRequestHide at ORIGIN_CLIENT_HIDE_SOFT_INPUT reason HIDE_SOFT_INPUT_BY_INSETS_API
02-19 21:13:35.574  9242  9242 I ImeTracker: com.toasterofbread.spmp.debug:9cc011bc: onHidden
02-19 21:13:35.931  9242  9242 I ImeTracker: com.toasterofbread.spmp.debug:2c9dd270: onRequestHide at ORIGIN_CLIENT_HIDE_SOFT_INPUT reason HIDE_SOFT_INPUT
02-19 21:13:41.704  9242  9242 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=androidx.activity.OnBackPressedDispatcher$Api34Impl$createOnBackAnimationCallback$1@c691d75
02-19 21:13:41.909  9242  9255 W read.spmp.debug: Cleared Reference was only reachable from finalizer (only reported once)
02-19 21:13:42.106  9242  9257 W read.spmp.debug: ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~-X8TYLv6jvGikNcN4M7Bow==/com.google.android.webview-z7zAMNEV0EZbtKSqgpC5eg==/base.apk' with 1 weak references
02-19 21:13:42.106  9242  9257 W read.spmp.debug: ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~-X8TYLv6jvGikNcN4M7Bow==/com.google.android.webview-z7zAMNEV0EZbtKSqgpC5eg==/split_config.en.apk' with 1 weak references
02-19 21:14:03.258  9242  9242 I ImeTracker: com.toasterofbread.spmp.debug:b4fd6b37: onRequestShow at ORIGIN_CLIENT_SHOW_SOFT_INPUT reason SHOW_SOFT_INPUT
02-19 21:14:03.258  9242  9242 D InputMethodManager: showSoftInput() view=android.webkit.WebView{40d7418 VFEDHVC.. .F...... 0,0-1028,2400 aid=1073741826} flags=0 reason=SHOW_SOFT_INPUT
02-19 21:14:03.285  9242  9242 I AssistStructure: Flattened final assist data: 2384 bytes, containing 1 windows, 5 views
02-19 21:14:03.376  9242  9242 D InsetsController: show(ime(), fromIme=true)
02-19 21:14:03.702  9242  9242 I ImeTracker: com.toasterofbread.spmp.debug:b4fd6b37: onShown
02-19 21:14:04.569  9242  9242 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=ImeCallback=ImeOnBackInvokedCallback@142718725 Callback=android.window.IOnBackInvokedCallback$Stub$Proxy@a27a01a
02-19 21:14:04.701  9242  9242 I ImeTracker: com.toasterofbread.spmp.debug:1a446e0a: onCancelled at PHASE_CLIENT_APPLY_ANIMATION
02-19 21:14:04.955  9242  9242 I ImeTracker: com.toasterofbread.spmp.debug:33e82f94: onRequestHide at ORIGIN_CLIENT_HIDE_SOFT_INPUT reason HIDE_SOFT_INPUT_BY_INSETS_API
02-19 21:14:04.956  9242  9242 I ImeTracker: com.toasterofbread.spmp.debug:bc1eaf55: onHidden
02-19 21:14:05.241  9242  9242 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=androidx.activity.OnBackPressedDispatcher$Api34Impl$createOnBackAnimationCallback$1@c691d75
02-19 21:14:24.682  9242  9242 D InsetsController: show(ime(), fromIme=true)
02-19 21:14:25.019  9242  9242 I ImeTracker: com.toasterofbread.spmp.debug:f04fb36c: onShown
02-19 21:14:27.986  9242  9242 D CompatibilityChangeReporter: Compat change id reported: 210923482; UID 10469; state: ENABLED
02-19 21:14:28.740  9242  9242 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=android.widget.PopupWindow$PopupDecorView$$ExternalSyntheticLambda0@7a0a77
02-19 21:14:28.751  9242  9242 E DecorView[]: Destroying unexpected ActionMode instance of TYPE_FLOATING; com.android.internal.view.FloatingActionMode@fbfb668 was not the current floating action mode! Expected null
02-19 21:14:29.006  9242  9242 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=android.widget.PopupWindow$PopupDecorView$$ExternalSyntheticLambda0@81ea7a1
02-19 21:14:29.012  9242  9265 D OpenGLRenderer: endAllActiveAnimators on 0xb400007e31258720 (RippleDrawable) with handle 0xb400007e11280b00
02-19 21:14:29.597  9242  9242 I ImeTracker: com.toasterofbread.spmp.debug:eacdda8f: onRequestHide at ORIGIN_CLIENT_HIDE_SOFT_INPUT reason HIDE_SOFT_INPUT
02-19 21:14:29.606  9242  9589 W RemoteInputConnectionImpl: requestCursorUpdates on inactive InputConnection
02-19 21:14:29.647  9242  9242 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=ImeCallback=ImeOnBackInvokedCallback@142718725 Callback=android.window.IOnBackInvokedCallback$Stub$Proxy@117ab03
02-19 21:14:29.928  9242  9242 I ImeTracker: com.toasterofbread.spmp.debug:5536dd63: onRequestHide at ORIGIN_CLIENT_HIDE_SOFT_INPUT reason HIDE_SOFT_INPUT_BY_INSETS_API
02-19 21:14:29.929  9242  9242 I ImeTracker: com.toasterofbread.spmp.debug:eacdda8f: onHidden
02-19 21:14:35.487  9242  9474 I AAudio  : AAudioStreamBuilder_openStream() called ----------------------------------------
02-19 21:14:35.487  9242  9474 I AudioStreamBuilder: rate   =  44100, channels  = 1, channelMask = 0x80000001, format   = 5, sharing = SH, dir = OUTPUT
02-19 21:14:35.487  9242  9474 I AudioStreamBuilder: device =      0, sessionId = -1, perfMode = 11, callback: ON with frames = 1024
02-19 21:14:35.487  9242  9474 I AudioStreamBuilder: usage  =      1, contentType = 0, inputPreset = 0, allowedCapturePolicy = 0
02-19 21:14:35.487  9242  9474 I AudioStreamBuilder: privacy sensitive = false, opPackageName = (null), attributionTag = (null)
02-19 21:14:35.488  9242  9474 D AudioStreamBuilder: build() MMAP not used because AAUDIO_PERFORMANCE_MODE_LOW_LATENCY not requested.
02-19 21:14:35.489  9242  9474 D read.spmp.debug: PlayerBase::PlayerBase()
02-19 21:14:35.489  9242  9474 D AudioStreamTrack: open(), request notificationFrames = 0, frameCount = 0
02-19 21:14:35.505  9242  9474 D AAudioStream: setState(s#1) from 0 to 2
02-19 21:14:35.507  9242  9474 I AAudio  : AAudioStreamBuilder_openStream() returns 0 = AAUDIO_OK for s#1 ----------------
02-19 21:14:35.514  9242  9474 D AAudio  : AAudioStream_requestStart(s#1) called --------------
02-19 21:14:35.514  9242  9474 D AAudioStream: setState(s#1) from 2 to 3
02-19 21:14:35.519  9242  9474 D AAudio  : AAudioStream_requestStart(s#1) returned 0 ---------
02-19 21:14:35.523  9242 10512 D AudioStreamLegacy: onAudioDeviceUpdate(deviceId = 3)
02-19 21:14:35.574  9242 10612 D AAudioStream: setState(s#1) from 3 to 4
02-19 21:14:36.017  9242  9474 W cr_media: Requires MODIFY_AUDIO_SETTINGS and RECORD_AUDIO. No audio device will be available for recording
02-19 21:14:37.536  9242  9474 W cr_media: Requires MODIFY_AUDIO_SETTINGS and RECORD_AUDIO. No audio device will be available for recording
02-19 21:14:38.166  9242  9474 D AAudio  : AAudioStream_requestStop(s#1) called
02-19 21:14:38.167  9242  9474 D AAudioStream: setState(s#1) from 4 to 9
02-19 21:14:38.167  9242  9474 D AudioTrack: stop(18531): called with 120862 frames delivered
02-19 21:14:38.168  9242  9474 D AAudioStream: setState(s#1) from 9 to 10
02-19 21:14:38.832  9242 10558 D TrafficStats: tagSocket(337) with statsTag=0xffffffff, statsUid=-1
02-19 21:14:39.385  9242 10652 D TrafficStats: tagSocket(265) with statsTag=0xffffffff, statsUid=-1
02-19 21:14:39.385  9242 10653 D TrafficStats: tagSocket(271) with statsTag=0xffffffff, statsUid=-1
02-19 21:14:39.669  9242  9242 D Compose Focus: Owner FocusChanged(true)
02-19 21:14:40.476  9242  9286 D TrafficStats: tagSocket(105) with statsTag=0xffffffff, statsUid=-1
02-19 21:14:41.515  9242  9282 W SpMp    : String key 'Latest episodes' of type OWN_CHANNEL has not been localised (source lang=en-GB)
02-19 21:14:41.516  9242  9282 W SpMp    : String key 'Podcasts' of type OWN_CHANNEL has not been localised (source lang=en-GB)
02-19 21:14:41.620  9242 10618 D TrafficStats: tagSocket(115) with statsTag=0xffffffff, statsUid=-1
02-19 21:14:41.637  9242 10558 D TrafficStats: tagSocket(108) with statsTag=0xffffffff, statsUid=-1
02-19 21:14:43.170  9242  9474 D AAudio  : AAudioStream_requestStop(s#1) called
02-19 21:14:44.135  9242  9242 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=androidx.activity.OnBackPressedDispatcher$Api34Impl$createOnBackAnimationCallback$1@c691d75
02-19 21:14:44.171  9242  9474 D AAudio  : AAudioStream_close(s#1) called ---------------
02-19 21:14:44.171  9242  9474 D AAudioStream: setState(s#1) from 10 to 11
02-19 21:14:44.172  9242  9474 D AAudioStream: setState(s#1) from 11 to 12
02-19 21:14:44.172  9242  9474 D AAudioStream: ~AudioStream(s#1) mPlayerBase strongCount = 2
02-19 21:14:44.172  9242  9474 D AAudio  : AAudioStream_close(s#1) returned 0 ---------
02-19 21:14:44.661  9242  9242 I Choreographer: Skipped 35 frames!  The application may be doing too much work on its main thread.
02-19 21:14:44.673  9242  9284 D TrafficStats: tagSocket(118) with statsTag=0xffffffff, statsUid=-1
02-19 21:14:44.674  9242 10559 D TrafficStats: tagSocket(122) with statsTag=0xffffffff, statsUid=-1
02-19 21:14:44.676  9242 10558 D TrafficStats: tagSocket(110) with statsTag=0xffffffff, statsUid=-1
02-19 21:14:44.676  9242  9285 D TrafficStats: tagSocket(119) with statsTag=0xffffffff, statsUid=-1
02-19 21:14:44.676  9242  9344 D TrafficStats: tagSocket(113) with statsTag=0xffffffff, statsUid=-1
02-19 21:14:44.678  9242 10673 D TrafficStats: tagSocket(112) with statsTag=0xffffffff, statsUid=-1
02-19 21:14:44.681  9242  9345 D TrafficStats: tagSocket(109) with statsTag=0xffffffff, statsUid=-1
02-19 21:14:44.681  9242 10672 D TrafficStats: tagSocket(159) with statsTag=0xffffffff, statsUid=-1
02-19 21:14:44.877  9242  9434 I OpenGLRenderer: Davey! duration=787ms; Flags=0, FrameTimelineVsyncId=255070753, IntendedVsync=753912956285912, Vsync=753913538554942, InputEventId=0, HandleInputStart=753913541134719, AnimationStart=753913541137934, PerformTraversalsStart=753913640380894, DrawStart=753913640596959, FrameDeadline=753913505475368, FrameInterval=753913540829299, FrameStartTime=16636258, SyncQueued=753913737942174, SyncStart=753913738095047, IssueDrawCommandsStart=753913738445226, SwapBuffers=753913739482701, FrameCompleted=753913744264236, DequeueBufferDuration=15869, QueueBufferDuration=390910, GpuCompleted=753913744264236, SwapBuffersCompleted=753913739960606, DisplayPresentTime=753908293858024, CommandSubmissionCompleted=753913739482701, 
02-19 21:14:48.041  9242  9255 I read.spmp.debug: Background concurrent mark compact GC freed 820573(32MB) AllocSpace objects, 91(3608KB) LOS objects, 75% free, 15MB/60MB, paused 299us,6.703ms total 126.843ms
02-19 21:14:49.022  9242  9285 D TrafficStats: tagSocket(108) with statsTag=0xffffffff, statsUid=-1
02-19 21:14:49.022  9242 10673 D TrafficStats: tagSocket(115) with statsTag=0xffffffff, statsUid=-1
02-19 21:14:49.023  9242  9345 D TrafficStats: tagSocket(242) with statsTag=0xffffffff, statsUid=-1
02-19 21:14:49.025  9242 10618 D TrafficStats: tagSocket(118) with statsTag=0xffffffff, statsUid=-1
02-19 21:14:49.025  9242 10675 D TrafficStats: tagSocket(277) with statsTag=0xffffffff, statsUid=-1
02-19 21:14:49.025  9242  9286 D TrafficStats: tagSocket(288) with statsTag=0xffffffff, statsUid=-1
02-19 21:14:49.025  9242  9282 D TrafficStats: tagSocket(197) with statsTag=0xffffffff, statsUid=-1
02-19 21:14:49.026  9242  9283 D TrafficStats: tagSocket(282) with statsTag=0xffffffff, statsUid=-1
02-19 21:14:49.026  9242 10676 D TrafficStats: tagSocket(289) with statsTag=0xffffffff, statsUid=-1
02-19 21:14:49.026  9242 10559 D TrafficStats: tagSocket(290) with statsTag=0xffffffff, statsUid=-1
02-19 21:14:49.026  9242 10674 D TrafficStats: tagSocket(298) with statsTag=0xffffffff, statsUid=-1
02-19 21:14:49.026  9242 10672 D TrafficStats: tagSocket(295) with statsTag=0xffffffff, statsUid=-1
02-19 21:14:49.026  9242  9284 D TrafficStats: tagSocket(305) with statsTag=0xffffffff, statsUid=-1
02-19 21:14:49.067  9242  9358 D TrafficStats: tagSocket(101) with statsTag=0xffffffff, statsUid=-1
02-19 21:14:49.071  9242 10558 D TrafficStats: tagSocket(344) with statsTag=0xffffffff, statsUid=-1
02-19 21:14:52.357  9242  9285 D TrafficStats: tagSocket(101) with statsTag=0xffffffff, statsUid=-1
02-19 21:14:52.357  9242 10673 D TrafficStats: tagSocket(150) with statsTag=0xffffffff, statsUid=-1
02-19 21:14:53.337  9242  9242 W System.err: kotlin.NotImplementedError: An operation is not implemented.
02-19 21:14:53.337  9242  9242 W System.err: 	at com.toasterofbread.spmp.ui.layout.playlistpage.PlaylistInteractionBarKt$PlaylistInteractionBar$1$2$1$3$1$1$2$2$1.invoke(PlaylistInteractionBar.kt:114)
02-19 21:14:53.337  9242  9242 W System.err: 	at com.toasterofbread.spmp.ui.layout.playlistpage.PlaylistInteractionBarKt$PlaylistInteractionBar$1$2$1$3$1$1$2$2$1.invoke(PlaylistInteractionBar.kt:112)
02-19 21:14:53.337  9242  9242 W System.err: 	at androidx.compose.foundation.ClickablePointerInputNode$pointerInput$3.invoke-k-4lQ0M(Clickable.kt:895)
02-19 21:14:53.337  9242  9242 W System.err: 	at androidx.compose.foundation.ClickablePointerInputNode$pointerInput$3.invoke(Clickable.kt:889)
02-19 21:14:53.337  9242  9242 W System.err: 	at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1.invokeSuspend(TapGestureDetector.kt:255)
02-19 21:14:53.337  9242  9242 W System.err: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
02-19 21:14:53.337  9242  9242 W System.err: 	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:179)
02-19 21:14:53.337  9242  9242 W System.err: 	at kotlinx.coroutines.DispatchedTaskKt.disp

</details>

### SpMp version

0.2.4-debug

### SpMp platform

Android arm64

### OS version

Android 14

**Comment by toasterofbread** [comment]
That's a button I added ages ago but never implemented. It doesn't really have a use so I've removed it in a7eeaa0.
