### ISSUE TITLE
Download (app crash)

### ISSUE THREAD

**Issue by D3Y4N4** [toasterofbread/spmp#238]
### Checklist

- [X] I am able to reproduce the bug with the latest debug version ([Android](https://nightly.link/toasterofbread/spmp/workflows/build-android/main), [Linux](https://nightly.link/toasterofbread/spmp/workflows/build-linux/main), [Windows](https://nightly.link/toasterofbread/spmp/workflows/build-windows/main))
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

1.When click on download icon to download app.
2.Whole screen gets blacked and app doesn't respond.
3.But background music doesn't stop even after crash.

### Expected behavior

May be it's a bug.

### Actual behavior

!

### Logs

No logs

### SpMp version

0.2.4

### SpMp platform

Android

### OS version

Android 14 (one ui)

**Comment by D3Y4N4** [comment]
2024-02-23 09:33:03.330 15963 15963 com.toasterofbread.spmp E AndroidRuntime : FATAL EXCEPTION: main
Process: com.toasterofbread.spmp, PID: 15963
java.lang.RuntimeException: Unable to create service com.toasterofbread.spmp.PlayerDownloadService: java.lang.NullPointerException
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:5111)
	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2506)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8893)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
Caused by: java.lang.NullPointerException
	at com.toasterofbread.spmp.resources.ResourcesKt.getStrings(Unknown Source:2)
	at com.toasterofbread.spmp.resources.ResourcesKt.getString(Unknown Source:5)
	at com.toasterofbread.spmp.PlayerDownloadService.onCreate(SourceFile:61)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:5098)
	...

**Comment by D3Y4N4** [comment]
Another log: 

2024-02-23 09:33:03.338 1306 4569 system I am_crash : [15963,0,com.toasterofbread.spmp,818462276,java.lang.NullPointerException,Unable to create service com.toasterofbread.spmp.PlayerDownloadService: java.lang.NullPointerException,NULL,2,0]


Doing great job!👍 
Looking forward for further information.

**Comment by D3Y4N4** [comment]
Wow!
The next 0.3.0 patch fixed it.
Thanks. But when I download the song other than the spmp's library into my phone storage it cancelled the download.
Hope you will fix it.😍
