### ISSUE TITLE
Error custom download

### ISSUE THREAD

**Issue by ChassterTP** [toasterofbread/spmp#246]
java.lang.IllegalStateException: Check failed.
	at com.toasterofbread.composekit.platform.PlatformFile.moveTo(Unknown Source:30)
	at com.toasterofbread.spmp.platform.download.SongDownloader$performDownload$2.invokeSuspend(SourceFile:415)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:107)
	at androidx.fragment.app.Fragment$4.run(SourceFile:105)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:94)

**Comment by toasterofbread** [comment]
Please fill the [issue template](https://github.com/toasterofbread/spmp/issues/new?assignees=&labels=Bug&projects=&template=bug_report.yml) with all required information
