### ISSUE TITLE
Error Custom Path Download

### ISSUE THREAD

**Issue by ChassterTP** [toasterofbread/spmp#247]
### Checklist

- [X] I am able to reproduce the bug with the latest debug version ([Android](https://nightly.link/toasterofbread/spmp/workflows/build-android/main), [Linux](https://nightly.link/toasterofbread/spmp/workflows/build-linux/main), [Windows](https://nightly.link/toasterofbread/spmp/workflows/build-windows/main))
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

i use a custom path for donwloading any songs. The custom path was in my music folder.

### Expected behavior

Maybe I'll see the song donwloaded on music folder

### Actual behavior

It didn't download any song.

### Screenshots / recordings

![Screenshot_20240302-173135](https://github.com/toasterofbread/spmp/assets/110549152/d01c434f-5e7c-4e4f-8d07-2f740a5225ef)

### Logs

java.lang.IllegalStateException: Check failed.
	at com.toasterofbread.composekit.platform.PlatformFile.moveTo(Unknown Source:30)
	at com.toasterofbread.spmp.platform.download.SongDownloader$performDownload$2.invokeSuspend(SourceFile:415)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:107)
	at androidx.fragment.app.Fragment$4.run(SourceFile:105)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:94)

### SpMp version

0.3.0

### SpMp platform

Android

### OS version

Android 12

**Comment by ChassterTP** [comment]
oh and also if i downloaded any song, the notif in the screenshot is still shown and its still says downloading even if its 100%

**Comment by toasterofbread** [comment]
The error message given when that function fails was improved in ca9d06a, but your error message seems to be from v0.3.0. Please provide the error message displayed in the latest nightly build.
