### ISSUE TITLE
Nightly Build: Error occurred while trying to start a local server on windows nightly build.

### ISSUE THREAD

**Issue by PopCat19** [toasterofbread/spmp#265]
### Checklist

- [X] I am able to reproduce the bug with the latest debug version ([Android](https://nightly.link/toasterofbread/spmp/workflows/build-android/main), [Linux](https://nightly.link/toasterofbread/spmp/workflows/build-linux/main), [Windows](https://nightly.link/toasterofbread/spmp/workflows/build-windows/main))
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### **This bug does not occur on [spmp-v0.3.0-windows-x86_64.exe](https://github.com/toasterofbread/spmp/releases/download/v0.3.0/spmp-v0.3.0-windows-x86_64.exe) from the [v0.3.0 release](https://github.com/toasterofbread/spmp/releases/tag/v0.3.0)**

1. Install spmp-v0.3.0-windows-x86_64.exe from the first link of [latest nightly release](https://nightly.link/toasterofbread/spmp/workflows/build-windows/main/spmp-windows-release.zip).
![image](https://github.com/toasterofbread/spmp/assets/104473808/cc0aba4a-d366-436c-a70c-256c55efbe18)

2. Add `preferences.json` with `{"SYSTEM_FONT":1}` in `%localappdata%` 
https://github.com/toasterofbread/spmp/issues/263#issuecomment-2016517544
![image](https://github.com/toasterofbread/spmp/assets/104473808/d2e2cc5c-00e8-45cb-86df-185c55c1dd0e)

3. Launched spmp.
![image](https://github.com/toasterofbread/spmp/assets/104473808/20fbcbe0-4368-4833-ae3c-7de1c9b78701)

4. Clicked "Start local server".
![image](https://github.com/toasterofbread/spmp/assets/104473808/02ca02f8-1504-4e28-ad00-1aa6c439b926)

### Expected behavior

It should start the local server.

### Actual behavior

An error occurred while trying to start a local server.

### Screenshots / recordings

![image](https://github.com/toasterofbread/spmp/assets/104473808/0180e237-9a35-4def-a5bb-71d9ed8f333d)
![image](https://github.com/toasterofbread/spmp/assets/104473808/d2e2cc5c-00e8-45cb-86df-185c55c1dd0e)
![image](https://github.com/toasterofbread/spmp/assets/104473808/20fbcbe0-4368-4833-ae3c-7de1c9b78701)
![image](https://github.com/toasterofbread/spmp/assets/104473808/02ca02f8-1504-4e28-ad00-1aa6c439b926)

### Logs

```
java.lang.RuntimeException: Local server command not set
	at com.toasterofbread.spmp.platform.splash.ExtraLoadingContent_desktopKt.SplashExtraLoadingContent$startServer(ExtraLoadingContent.desktop.kt:104)
	at com.toasterofbread.spmp.platform.splash.ExtraLoadingContent_desktopKt.access$SplashExtraLoadingContent$startServer(ExtraLoadingContent.desktop.kt:1)
	at com.toasterofbread.spmp.platform.splash.ExtraLoadingContent_desktopKt$SplashExtraLoadingContent$3$1$1.invoke(ExtraLoadingContent.desktop.kt:129)
	at com.toasterofbread.spmp.platform.splash.ExtraLoadingContent_desktopKt$SplashExtraLoadingContent$3$1$1.invoke(ExtraLoadingContent.desktop.kt:128)
	at androidx.compose.foundation.ClickablePointerInputNode$pointerInput$3.invoke-k-4lQ0M(Clickable.kt:898)
	at androidx.compose.foundation.ClickablePointerInputNode$pointerInput$3.invoke(Clickable.kt:891)
	at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1.invokeSuspend(TapGestureDetector.kt:258)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:175)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:164)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:470)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:504)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:493)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:364)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl$PointerEventHandlerCoroutine.offerPointerEvent(SuspendingPointerInputFilter.kt:672)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.dispatchPointerEvent(SuspendingPointerInputFilter.kt:549)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.onPointerEvent-H0pRuoY(SuspendingPointerInputFilter.kt:571)
	at androidx.compose.foundation.AbstractClickablePointerInputNode.onPointerEvent-H0pRuoY(Clickable.kt:857)
	at androidx.compose.foundation.AbstractClickableNode.onPointerEvent-H0pRuoY(Clickable.kt:705)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:326)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:312)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:312)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:312)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:312)
	at androidx.compose.ui.input.pointer.NodeParent.dispatchMainEventPass(HitPathTracker.kt:185)
	at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(HitPathTracker.kt:104)
	at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-BIzXfog(PointerInputEventProcessor.kt:97)
	at androidx.compose.ui.platform.SkiaBasedOwner.processPointerInput-gBdvCQM$ui(SkiaBasedOwner.skiko.kt:362)
	at androidx.compose.ui.platform.SkiaBasedOwner.processPointerInput-gBdvCQM$ui$default(SkiaBasedOwner.skiko.kt:355)
	at androidx.compose.ui.ComposeScene.processRelease(ComposeScene.skiko.kt:739)
	at androidx.compose.ui.ComposeScene.processPointerInput(ComposeScene.skiko.kt:698)
	at androidx.compose.ui.ComposeScene.access$processPointerInput(ComposeScene.skiko.kt:68)
	at androidx.compose.ui.ComposeScene$syntheticEventSender$1.invoke(ComposeScene.skiko.kt:299)
	at androidx.compose.ui.ComposeScene$syntheticEventSender$1.invoke(ComposeScene.skiko.kt:299)
	at androidx.compose.ui.SyntheticEventSender.sendInternal(SyntheticEventSender.kt:179)
	at androidx.compose.ui.SyntheticEventSender.send(SyntheticEventSender.kt:83)
	at androidx.compose.ui.ComposeScene.sendPointerEvent-WlEVilQ(ComposeScene.skiko.kt:668)
	at androidx.compose.ui.ComposeScene.sendPointerEvent-BGSDPeU(ComposeScene.skiko.kt:610)
	at androidx.compose.ui.ComposeScene.sendPointerEvent-BGSDPeU$default(ComposeScene.skiko.kt:593)
	at androidx.compose.ui.awt.ComposeBridge_desktopKt.onMouseEvent(ComposeBridge.desktop.kt:440)
	at androidx.compose.ui.awt.ComposeBridge_desktopKt.access$onMouseEvent(ComposeBridge.desktop.kt:1)
	at androidx.compose.ui.awt.ComposeBridge$onMouseEvent$1.invoke(ComposeBridge.desktop.kt:271)
	at androidx.compose.ui.awt.ComposeBridge$onMouseEvent$1.invoke(ComposeBridge.desktop.kt:264)
	at androidx.compose.ui.awt.ComposeBridge.catchExceptions(ComposeBridge.desktop.kt:150)
	at androidx.compose.ui.awt.ComposeBridge.onMouseEvent(ComposeBridge.desktop.kt:264)
	at androidx.compose.ui.awt.ComposeBridge.access$onMouseEvent(ComposeBridge.desktop.kt:64)
	at androidx.compose.ui.awt.ComposeBridge$attachComposeToComponent$3.mouseReleased(ComposeBridge.desktop.kt:245)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```

### SpMp version

0.3.0

### SpMp platform

Windows

### OS version

Microsoft Windows 10 Home (x64) Build 19045.4170 (22H2)

### Additional information

**This bug does not occur on [spmp-v0.3.0-windows-x86_64.exe](https://github.com/toasterofbread/spmp/releases/download/v0.3.0/spmp-v0.3.0-windows-x86_64.exe) from the [v0.3.0 release](https://github.com/toasterofbread/spmp/releases/tag/v0.3.0)**

Unable to copy error log via throw button due to error window preventing me to interact with the logs. 
![image](https://github.com/toasterofbread/spmp/assets/104473808/64768d89-48b2-4035-9e83-32b1a67ee04a)

I copied the logs from the RuntimeException window instead.
![image](https://github.com/toasterofbread/spmp/assets/104473808/86acc2d9-f357-4b02-9955-edd45d7c6992)

**Comment by toasterofbread** [comment]
This is intended behaviour, as the command to run the local server needs to be set manually from `Configure connection`. This doesn't occur on v0.3.0 because releases come packaged with the server which is run automatically (yeah, this could probably be made clearer in the UI).

The [v0.3.0 server release](https://github.com/toasterofbread/spmp-server/releases/tag/v0.3.0) should work with the nightly SpMp release, or you can just use v0.3.0 of SpMp, or wait for the next release which should (hopefully) be in the next few days.
