### ISSUE TITLE
Account switcher response parsing failed ` {"code":"SUCCESS","data":{"responseContext":{...`

### ISSUE THREAD

**Issue by JellyBrick** [toasterofbread/spmp#266]
### Checklist

- [X] I am able to reproduce the bug with the latest debug version ([Android](https://nightly.link/toasterofbread/spmp/workflows/build-android/main), [Linux](https://nightly.link/toasterofbread/spmp/workflows/build-linux/main), [Windows](https://nightly.link/toasterofbread/spmp/workflows/build-windows/main))
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

1. Login with `Headers`
(env: KR)

### Expected behavior

It must be logged in.

### Actual behavior

`RuntimeException` is thrown.

### Screenshots / recordings

![image](https://github.com/toasterofbread/spmp/assets/16558115/14e81d00-f690-41dd-b219-d6834c13f604)
![image](https://github.com/toasterofbread/spmp/assets/16558115/1464085c-e67a-43bc-a25f-c0004db1866b)

### Logs

```java
Caused by: kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 2: Encountered an unknown key 'code' at path: $
Use 'ignoreUnknownKeys = true' in 'Json {}' builder to ignore unknown keys.
JSON input: {"code":"SUCCESS","data":{"respo.....
	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:598)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.failOnUnknownKey(AbstractJsonLexer.kt:593)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.handleUnknown(StreamingJsonDecoder.kt:257)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeObjectIndex(StreamingJsonDecoder.kt:243)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeElementIndex(StreamingJsonDecoder.kt:178)
	at com.toasterofbread.spmp.youtubeapi.AccountSwitcherEndpoint$$serializer.deserialize(AccountSwitcherEndpoint.kt:6)
	at com.toasterofbread.spmp.youtubeapi.AccountSwitcherEndpoint$$serializer.deserialize(AccountSwitcherEndpoint.kt:6)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:107)
	at com.toasterofbread.spmp.ui.layout.youtubemusiclogin.YoutubeMusicLoginPage.LoginPage$onHeadersProvided(YoutubeMusicLoginPage.kt:365)
	... 24 more

```

### SpMp version

0.3.0

### SpMp platform

Windows

### OS version

Windows 11

### Additional information

https://github.com/toasterofbread/spmp/blob/ffb5d747732196d2740763fd1ccaf3d45fe3be27/shared/src/commonMain/kotlin/com/toasterofbread/spmp/youtubeapi/AccountSwitcherEndpoint.kt#L7

->
```kotlin
data class AccountSwitcherEndpoint(val code: String, val data: Data) {
```

or 

Set `ignoreUnknownKeys` as true.

**Comment by toasterofbread** [comment]
Thanks, the project migrated to Ktor and Kotlinx serialization recently so there are still a few lingering bugs.
