### ISSUE TITLE
problems with playback  

### ISSUE THREAD

**Issue by m3ru0** [toasterofbread/spmp#275]
### Checklist

- [X] I am able to reproduce the bug with the latest debug version ([Android](https://nightly.link/toasterofbread/spmp/workflows/build-android/main), [Linux](https://nightly.link/toasterofbread/spmp/workflows/build-linux/main), [Windows](https://nightly.link/toasterofbread/spmp/workflows/build-windows/main))
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

Before starting I want to clarify that I am someone who speaks Spanish and I am using the translator for this message (in case you find any inconsistency in the message) 
Now yes, I downloaded the app from the different apks that there are, I add the songs normally but when I listen to them and open the playlist it doesn't let me select them to listen to them again. 

### Expected behavior

I'm supposed to be able to listen to it again. 

### Actual behavior

It doesn't let you listen to them again, I tried the songs themselves and tried videos but none of them let me listen to them again after having done it once.

### Screenshots / recordings

![Screenshot_20240325_182556](https://github.com/toasterofbread/spmp/assets/164958656/62441f62-293d-46d6-80bd-18a4c1c71042)

### Logs

java.lang.RuntimeException: Song has no related_browse_id
	at com.toasterofbread.spmp.youtubeapi.impl.youtubemusic.endpoint.YTMSongRelatedContentEndpoint$getSongRelated$2.invokeSuspend(SourceFile:207)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Unknown Source:6)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(SourceFile:23)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:31)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:107)
	at androidx.fragment.app.Fragment$4.run(SourceFile:105)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:94)

### SpMp version

0.3.0

### SpMp platform

Android

### OS version

Android 13 One UI 5.1

### Additional information

I have nothing more to add, I just thank the creator for having such a good project and I hope it prospers and reaches more.

**Comment by m3ru0** [comment]
OK
