### ISSUE TITLE
Can't log in (CancellationException)

### ISSUE THREAD

**Issue by Bluscream** [toasterofbread/spmp#280]
### Checklist

- [X] I am able to reproduce the bug with the latest debug version ([Android](https://nightly.link/toasterofbread/spmp/workflows/build-android/main), [Linux](https://nightly.link/toasterofbread/spmp/workflows/build-linux/main), [Windows](https://nightly.link/toasterofbread/spmp/workflows/build-windows/main))
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

1. Try logging in to youtube
2. Select account

### Expected behavior

Login

### Actual behavior

Error popup

### Screenshots / recordings

![scrcpy_Au7sfNzyh8](https://github.com/toasterofbread/spmp/assets/3318223/c532996f-7511-49e3-a18b-b1c589d851f5)
![scrcpy_TBmHHRM7Zb](https://github.com/toasterofbread/spmp/assets/3318223/21dc6519-76d6-47ef-824b-8dc341c8f206)
![scrcpy_USTgiXoQWT](https://github.com/toasterofbread/spmp/assets/3318223/bd587531-db54-4b1b-a798-1e616ff25db5)

### Logs

couldn't get logcat to work, sorry im not a dev

<!-- #### clicking on account when login:
```log
.
´´´ -->

#### clicking on upload log:
```log
java.lang.IllegalStateException: Fail to prepare request body for sending. 
The body type is: class java.util.Collections$SingletonMap (Kotlin reflection is not available), with Content-Type: null.

If you expect serialized body, please check that you have installed the corresponding plugin(like `ContentNegotiation`) and set `Content-Type` header.
	at io.ktor.client.engine.HttpClientEngine$install$1.invokeSuspend(SourceFile:256)
	at io.ktor.client.engine.HttpClientEngine$install$1.invoke(SourceFile:4)
	at io.ktor.client.engine.HttpClientEngine$install$1.invoke(SourceFile:5)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SourceFile:36)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SourceFile:28)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceedWith(SourceFile:8)
	at io.ktor.client.plugins.HttpCallValidator$Companion$install$1.invokeSuspend(SourceFile:161)
	at io.ktor.client.plugins.HttpCallValidator$Companion$install$1.invoke(SourceFile:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SourceFile:36)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SourceFile:28)
	at io.ktor.client.HttpClient$4.invokeSuspend(SourceFile:197)
	at io.ktor.client.HttpClient$4.invoke(SourceFile:42)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SourceFile:36)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SourceFile:28)
	at io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SourceFile:24)
	at io.ktor.util.pipeline.Pipeline.execute(SourceFile:190)
	at io.ktor.client.HttpClient.execute$ktor_client_core(SourceFile:64)
	at io.ktor.client.statement.HttpStatement.executeUnsafe(Unknown Source:64)
	at io.ktor.client.statement.HttpStatement.execute(SourceFile:1)
	at io.ktor.client.statement.HttpStatement.execute(SourceFile:2)
	at com.toasterofbread.spmp.ui.component.ErrorInfoDisplayKt.uploadErrorToPasteEe(SourceFile:341)
	at com.toasterofbread.spmp.ui.component.ErrorInfoDisplayKt.uploadErrorToPasteEe$default(Unknown Source:19)
	at com.toasterofbread.spmp.ui.component.ErrorInfoDisplayKt$ExpandedContent$2$1$1$1$2$1.invokeSuspend(SourceFile:99)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:107)
	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(SourceFile:7)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(SourceFile:3)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8248)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

### SpMp version

0.3.1

### SpMp platform

Android

### OS version

Android 14 GSI

**Comment by toasterofbread** [comment]
Are you certain you've tested this on the latest build? Both of these should be fixed on main.

**Comment by Bluscream** [comment]
I downloaded the apk yesterday from gh releases, so yeah im sure

**Comment by toasterofbread** [comment]
The [Github releases](https://github.com/toasterofbread/spmp/releases) aren't the [latest debug builds](https://github.com/toasterofbread/spmp/actions). Please test the latest build to see if this bug is still present as stated in the issue template.

**Comment by Bluscream** [comment]
https://github.com/toasterofbread/spmp/actions/runs/8494126671/artifacts/1371948183 worked. I recommend building a release with the new fixes to resolve unnecessary confusion for end users trying to log in. Thanks for your work and help 👍🏻
