### ISSUE TITLE
Doesn't play the radio settings

### ISSUE THREAD

**Issue by RichSexum** [toasterofbread/spmp#292]
### Checklist

- [X] I am able to reproduce the bug with the latest debug version ([Android](https://nightly.link/toasterofbread/spmp/workflows/build-android/main), [Linux](https://nightly.link/toasterofbread/spmp/workflows/build-linux/main), [Windows](https://nightly.link/toasterofbread/spmp/workflows/build-windows/main))
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

Play any music, and the radio feature doesn't start.

### Expected behavior

java.lang.IllegalStateException: Fail to prepare request body for sending. 
The body type is: class java.util.Collections$SingletonMap (Kotlin reflection is not available), with Content-Type: null.

If you expect serialized body, please check that you have installed the corresponding plugin(like `ContentNegotiation`) and set `Content-Type` header.
	at io.ktor.client.engine.HttpClientEngine$install$1.invokeSuspend(SourceFile:256)
	at io.ktor.client.engine.HttpClientEngine$install$1.invoke(SourceFile:4)
	at io.ktor.client.engine.HttpClientEngine$install$1.invoke(SourceFile:5)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SourceFile:36)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SourceFile:28)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceedWith(SourceFile:8)
	at io.ktor.client.plugins.HttpCallValidator$Companion$install$1.invokeSuspend(SourceFile:161)
	at io.ktor.client.plugins.HttpCallValidator$Companion$install$1.invoke(SourceFile:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SourceFile:36)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SourceFile:28)
	at io.ktor.client.HttpClient$4.invokeSuspend(SourceFile:197)
	at io.ktor.client.HttpClient$4.invoke(SourceFile:42)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SourceFile:36)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SourceFile:28)
	at io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SourceFile:24)
	at io.ktor.util.pipeline.Pipeline.execute(SourceFile:190)
	at io.ktor.client.HttpClient.execute$ktor_client_core(SourceFile:64)
	at io.ktor.client.statement.HttpStatement.executeUnsafe(Unknown Source:64)
	at io.ktor.client.statement.HttpStatement.execute(SourceFile:1)
	at io.ktor.client.statement.HttpStatement.execute(SourceFile:2)
	at com.toasterofbread.spmp.ui.component.ErrorInfoDisplayKt.uploadErrorToPasteEe(SourceFile:341)
	at com.toasterofbread.spmp.ui.component.ErrorInfoDisplayKt.uploadErrorToPasteEe$default(Unknown Source:19)
	at com.toasterofbread.spmp.ui.component.ErrorInfoDisplayKt$ExpandedContent$2$1$1$1$2$1.invokeSuspend(SourceFile:99)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:107)
	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(SourceFile:7)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(SourceFile:3)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8250)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

### Actual behavior

java.lang.IllegalStateException: Fail to prepare request body for sending. 
The body type is: class java.util.Collections$SingletonMap (Kotlin reflection is not available), with Content-Type: null.

If you expect serialized body, please check that you have installed the corresponding plugin(like `ContentNegotiation`) and set `Content-Type` header.
	at io.ktor.client.engine.HttpClientEngine$install$1.invokeSuspend(SourceFile:256)
	at io.ktor.client.engine.HttpClientEngine$install$1.invoke(SourceFile:4)
	at io.ktor.client.engine.HttpClientEngine$install$1.invoke(SourceFile:5)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SourceFile:36)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SourceFile:28)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceedWith(SourceFile:8)
	at io.ktor.client.plugins.HttpCallValidator$Companion$install$1.invokeSuspend(SourceFile:161)
	at io.ktor.client.plugins.HttpCallValidator$Companion$install$1.invoke(SourceFile:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SourceFile:36)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SourceFile:28)
	at io.ktor.client.HttpClient$4.invokeSuspend(SourceFile:197)
	at io.ktor.client.HttpClient$4.invoke(SourceFile:42)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SourceFile:36)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SourceFile:28)
	at io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SourceFile:24)
	at io.ktor.util.pipeline.Pipeline.execute(SourceFile:190)
	at io.ktor.client.HttpClient.execute$ktor_client_core(SourceFile:64)
	at io.ktor.client.statement.HttpStatement.executeUnsafe(Unknown Source:64)
	at io.ktor.client.statement.HttpStatement.execute(SourceFile:1)
	at io.ktor.client.statement.HttpStatement.execute(SourceFile:2)
	at com.toasterofbread.spmp.ui.component.ErrorInfoDisplayKt.uploadErrorToPasteEe(SourceFile:341)
	at com.toasterofbread.spmp.ui.component.ErrorInfoDisplayKt.uploadErrorToPasteEe$default(Unknown Source:19)
	at com.toasterofbread.spmp.ui.component.ErrorInfoDisplayKt$ExpandedContent$2$1$1$1$2$1.invokeSuspend(SourceFile:99)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:107)
	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(SourceFile:7)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(SourceFile:3)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8250)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

### Screenshots / recordings

![Screenshot_2024-04-13-22-13-02-948_com toasterofbread spmp](https://github.com/toasterofbread/spmp/assets/92557186/006171f5-57bc-4cad-8afd-eaffe65aec55)
![Screenshot_2024-04-13-22-13-07-155_com toasterofbread spmp](https://github.com/toasterofbread/spmp/assets/92557186/ae72564a-95d2-4ec2-af9d-167448268962)

### Logs

java.lang.IllegalStateException: Fail to prepare request body for sending. 
The body type is: class java.util.Collections$SingletonMap (Kotlin reflection is not available), with Content-Type: null.

If you expect serialized body, please check that you have installed the corresponding plugin(like `ContentNegotiation`) and set `Content-Type` header.
	at io.ktor.client.engine.HttpClientEngine$install$1.invokeSuspend(SourceFile:256)
	at io.ktor.client.engine.HttpClientEngine$install$1.invoke(SourceFile:4)
	at io.ktor.client.engine.HttpClientEngine$install$1.invoke(SourceFile:5)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SourceFile:36)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SourceFile:28)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceedWith(SourceFile:8)
	at io.ktor.client.plugins.HttpCallValidator$Companion$install$1.invokeSuspend(SourceFile:161)
	at io.ktor.client.plugins.HttpCallValidator$Companion$install$1.invoke(SourceFile:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SourceFile:36)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SourceFile:28)
	at io.ktor.client.HttpClient$4.invokeSuspend(SourceFile:197)
	at io.ktor.client.HttpClient$4.invoke(SourceFile:42)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SourceFile:36)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SourceFile:28)
	at io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SourceFile:24)
	at io.ktor.util.pipeline.Pipeline.execute(SourceFile:190)
	at io.ktor.client.HttpClient.execute$ktor_client_core(SourceFile:64)
	at io.ktor.client.statement.HttpStatement.executeUnsafe(Unknown Source:64)
	at io.ktor.client.statement.HttpStatement.execute(SourceFile:1)
	at io.ktor.client.statement.HttpStatement.execute(SourceFile:2)
	at com.toasterofbread.spmp.ui.component.ErrorInfoDisplayKt.uploadErrorToPasteEe(SourceFile:341)
	at com.toasterofbread.spmp.ui.component.ErrorInfoDisplayKt.uploadErrorToPasteEe$default(Unknown Source:19)
	at com.toasterofbread.spmp.ui.component.ErrorInfoDisplayKt$ExpandedContent$2$1$1$1$2$1.invokeSuspend(SourceFile:99)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:107)
	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(SourceFile:7)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(SourceFile:3)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8250)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

### SpMp version

0.3.1

### SpMp platform

Android

### OS version

Android 12 miui 13

**Comment by JGlazunov** [comment]
Same problem

**Comment by toasterofbread** [comment]
YouTube changed something in their API, causing this issue in older builds. It was fixed in spmp by f3b9ce5b9fd07ad616611c160bd963fd520e14c3.

Expect a hotfix release containing the fix within the next week.
