### ISSUE TITLE
I get this error when trying to open the program

### ISSUE THREAD

**Issue by Aleyssia** [toasterofbread/spmp#297]
java.lang.UnsatisfiedLinkError: C:\Program Files\spmp\app\skiko-windows-x64.dll: Can't find dependent libraries

Stack trace:
java.lang.UnsatisfiedLinkError: C:\Program Files\spmp\app\skiko-windows-x64.dll: Can't find dependent libraries
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
	at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.base/java.lang.Runtime.load0(Unknown Source)
	at java.base/java.lang.System.load(Unknown Source)
	at org.jetbrains.skiko.Library.loadLibraryOrCopy(Library.kt:20)
	at org.jetbrains.skiko.Library.findAndLoad(Library.kt:85)
	at org.jetbrains.skiko.Library.load(Library.kt:59)
	at org.jetbrains.skia.impl.Library$Companion.staticLoad(Library.jvm.kt:12)
	at androidx.compose.ui.ConfigureSwingGlobalsForCompose_desktopKt.configureSwingGlobalsForCompose(ConfigureSwingGlobalsForCompose.desktop.kt:49)
	at androidx.compose.ui.ConfigureSwingGlobalsForCompose_desktopKt.configureSwingGlobalsForCompose$default(ConfigureSwingGlobalsForCompose.desktop.kt:38)
	at androidx.compose.ui.window.Application_desktopKt.application(Application.desktop.kt:110)
	at androidx.compose.ui.window.Application_desktopKt.application$default(Application.desktop.kt:105)
	at MainKt.main(main.kt:64)

**Comment by toasterofbread** [comment]
What app version/commit, and which OS version are you using? Also, what graphics card and drivers are you using? Please use the issue template for future reports.
