### ISSUE TITLE
Expected 1 service that handles android.intent.action.MEDIA_BUTTON, found 2

### ISSUE THREAD

**Issue by toasterofbread** [toasterofbread/spmp#312]
### Checklist

- [X] I am able to reproduce the bug with the latest debug version ([Android](https://nightly.link/toasterofbread/spmp/workflows/build-android/main), [Linux](https://nightly.link/toasterofbread/spmp/workflows/build-linux/main), [Windows](https://nightly.link/toasterofbread/spmp/workflows/build-windows/main))
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

Unknown, issue appeared to occur spontaneously while on the now playing page in portrait mode.

### Expected behavior

N/A

### Actual behavior

N/A

### Logs

2024-06-04 19:16:07.819 6507 6507 com.toasterofbread.spmp E AndroidRuntime : FATAL EXCEPTION: main
Process: com.toasterofbread.spmp, PID: 6507
java.lang.RuntimeException: Unable to start receiver androidx.media.session.MediaButtonReceiver: java.lang.IllegalStateException: Expected 1 service that handles android.intent.action.MEDIA_BUTTON, found 2
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4313)
	at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2150)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7925)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
Caused by: java.lang.IllegalStateException: Expected 1 service that handles android.intent.action.MEDIA_BUTTON, found 2
	at androidx.media.session.MediaButtonReceiver.getServiceComponentByAction(SourceFile:76)
	at androidx.media.session.MediaButtonReceiver.onReceive(SourceFile:24)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4304)
	... 9 more

### SpMp version

5b60fa3

### SpMp platform

Android

### OS version

Android 13

**Comment by toasterofbread** [comment]
Fixed by 6b39afe.
