### ISSUE TITLE
Not able to download songs !!

### ISSUE THREAD

**Issue by Peace-master2930** [toasterofbread/spmp#404]
java.lang.RuntimeException: No valid formats returned by getVideoFormats(K_fN5yysMHg)
	at com.toasterofbread.spmp.model.mediaitem.song.SongAudioQualityKt.getSongFormats(Unknown Source:141)
	at com.toasterofbread.spmp.model.mediaitem.song.SongAudioQualityKt$getSongFormats$1.invokeSuspend(Unknown Source:10)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:112)
	at androidx.core.app.ActivityRecreator$1.run(Unknown Source:98)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:95)

**Comment by toasterofbread** [comment]
Please create an issue using the bug report template, filling in all required information.
