### ISSUE TITLE
Logging into YouTube/Google account and clicking on its icon in the top right results in a "Not implemented Playlist blah blah" error

### ISSUE THREAD

**Issue by TicTecOfficial** [toasterofbread/spmp#61]
I also would like to add that after the error log appears and i exit it, the UI doesn't respond to any touches but music still plays.

p.s. sorry to keep disturbing you btw, promise this will be the last one until my curiousity breaks the app again 😂

**Comment by toasterofbread** [comment]
> I also would like to add that after the error log appears and i exit it, the UI doesn't respond to any touches but music still plays.

Yeah, that's a known issue that I don't think I can fix. The UI freezes because it runs in the main thread (which is what crashes), but the music keeps playing because it runs in another thread. The UI should start working again if you close the app and open it again.


> p.s. sorry to keep disturbing you btw, promise this will be the last one until my curiousity breaks the app again joy

No worries! I really appreciate the bug reports, this is the first time anyone's opened issues on one of my own projects which is really nice. I'm working on this app in most of my spare time anyway so it's good to have extra stuff to fix.

**Comment by TicTecOfficial** [comment]
> I can't reproduce this on my end, could you upload the error log please? I'm guessing the issue is probably due to something in your YouTube music profile layout that I haven't implemented in the app yet, because it doesn't appear in my profile.
> 
> If you can, could you add a screenshot of what the page looks like on the official YouTube music app/website when you go to 'Your channel'? Zoom out to get the whole page if you can. If you'd rather not send a screenshot, describing the layout should be fine as well.
> 
> It should look similar to this: ![2023-07-12-08-12-12](https://user-images.githubusercontent.com/44363049/252884607-2c56a690-79ee-4fd5-87be-7e54f9f504da.png)

![Screenshot_2023-07-12-18-44-09-71_801c3494cc30bc6d615367769f98046d](https://github.com/toasterofbread/spmp/assets/97348600/f93e71f4-4338-4cd8-9f8a-28df89d478fb)
![Screenshot_2023-07-12-18-44-16-37_801c3494cc30bc6d615367769f98046d](https://github.com/toasterofbread/spmp/assets/97348600/d646ed94-9581-4cf9-84bc-d516068e3c93)
![Screenshot_2023-07-12-18-44-19-50_801c3494cc30bc6d615367769f98046d](https://github.com/toasterofbread/spmp/assets/97348600/86eb6ab1-6096-40db-8759-de14e1dd1378)

this is my layout!

**Comment by TicTecOfficial** [comment]
also, the error log looks something like:

kotlin.NotImplementedError: Key: 'Playlists', Type: OWN_CHANNEL, Source lang: en
	at com.toasterofbread.spmp.resources.uilocalisation.LocalisedYoutubeString.getLocalised(Unknown Source:215)
	at com.toasterofbread.spmp.resources.uilocalisation.LocalisedYoutubeString.getString(Unknown Source:0)
	at com.toasterofbread.spmp.ui.component.MediaItemLayout.<init>(Unknown Source:35)
	at com.toasterofbread.spmp.ui.component.MediaItemLayout.<init>(Unknown Source:78)
	at com.toasterofbread.spmp.api.LoadMediaitemKt$processDefaultResponse$2.invokeSuspend(Unknown Source:1285)
	at com.toasterofbread.spmp.api.LoadMediaitemKt$processDefaultResponse$2.invoke(Unknown Source:8)
	at com.toasterofbread.spmp.api.LoadMediaitemKt$processDefaultResponse$2.invoke(Unknown Source:4)
	at androidx.appcompat.R$id.startUndispatchedOrReturn(Unknown Source:4)
	at okio.Utf8.withContext(Unknown Source:71)
	at com.toasterofbread.spmp.api.LoadMediaitemKt.processDefaultResponse(Unknown Source:13)
	at com.toasterofbread.spmp.api.LoadMediaitemKt$loadMediaItemData$2.invokeSuspend(Unknown Source:241)
	at com.toasterofbread.spmp.api.LoadMediaitemKt$loadMediaItemData$2.invoke(Unknown Source:8)
	at com.toasterofbread.spmp.api.LoadMediaitemKt$loadMediaItemData$2.invoke(Unknown Source:4)
	at androidx.appcompat.R$id.startUndispatchedOrReturn(Unknown Source:4)
	at okio.Utf8.withContext(Unknown Source:71)
	at com.toasterofbread.spmp.api.LoadMediaitemKt.loadMediaItemData(Unknown Source:76)
	at com.toasterofbread.spmp.model.mediaitem.MediaItem$loadGeneralData$2.invokeSuspend(Unknown Source:121)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:100)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(Unknown Source:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:79)
	Suppressed: coil.network.HttpException: [androidx.compose.ui.platform.MotionDurationScaleImpl@db65b50, androidx.compose.runtime.BroadcastFrameClock@6577149, StandaloneCoroutine{Cancelling}@f35aa4e, AndroidUiDispatcher@a11776f]

**Comment by toasterofbread** [comment]
Thanks for the info, should work now.
