### ISSUE TITLE
BUG: App throws the following error on load

### ISSUE THREAD

**Issue by emkay5771** [toasterofbread/spmp#64]
kotlin.NotImplementedError: Podcasts
	at com.toasterofbread.spmp.api.YoutubeiBrowseResponse.getHeaderChips(Unknown Source:163)
	at com.toasterofbread.spmp.api.HomeFeedKt$getHomeFeed$2.invokeSuspend(Unknown Source:637)
	at com.toasterofbread.spmp.api.HomeFeedKt$getHomeFeed$2.invoke(Unknown Source:8)
	at com.toasterofbread.spmp.api.HomeFeedKt$getHomeFeed$2.invoke(Unknown Source:4)
	at androidx.appcompat.R$id.startUndispatchedOrReturn(Unknown Source:4)
	at okio.Utf8.withContext(Unknown Source:71)
	at com.toasterofbread.spmp.api.HomeFeedKt.getHomeFeed(Unknown Source:65)
	at com.toasterofbread.spmp.ui.layout.mainpage.PlayerStateImplKt.loadFeedLayouts(Unknown Source:56)
	at com.toasterofbread.spmp.ui.layout.mainpage.PlayerStateImplKt.access$loadFeedLayouts(Unknown Source:0)
	at com.toasterofbread.spmp.ui.layout.mainpage.PlayerStateImpl$loadFeed$2.invokeSuspend(Unknown Source:173)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:100)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(Unknown Source:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:79)
	Suppressed: coil.network.HttpException: [androidx.compose.ui.platform.MotionDurationScaleImpl@25b3fbd, androidx.compose.runtime.BroadcastFrameClock@773e9b2, StandaloneCoroutine{Cancelling}@f3aed03, AndroidUiDispatcher@3a00480]

**Comment by toasterofbread** [comment]
Fixed! I also replaced the error throw with a warning message to prevent similar crashes.
