### ISSUE TITLE
error Code after logging in and let feed load

### ISSUE THREAD

**Issue by powl999** [toasterofbread/spmp#71]
kotlin.NotImplementedError: de
	at com.toasterofbread.spmp.resources.uilocalisation.AmountStringsKt.parseYoutubeSubscribersString(Unknown Source:95)
	at com.toasterofbread.spmp.api.LoadMediaitemKt$processDefaultResponse$2.invokeSuspend(Unknown Source:929)
	at com.toasterofbread.spmp.api.LoadMediaitemKt$processDefaultResponse$2.invoke(Unknown Source:8)
	at com.toasterofbread.spmp.api.LoadMediaitemKt$processDefaultResponse$2.invoke(Unknown Source:4)
	at androidx.core.R$dimen.startUndispatchedOrReturn(Unknown Source:4)
	at coil.util.-Contexts.withContext(Unknown Source:71)
	at com.toasterofbread.spmp.api.LoadMediaitemKt.processDefaultResponse(Unknown Source:13)
	at com.toasterofbread.spmp.api.LoadMediaitemKt$loadMediaItemData$2.invokeSuspend(Unknown Source:241)
	at com.toasterofbread.spmp.api.LoadMediaitemKt$loadMediaItemData$2.invoke(Unknown Source:8)
	at com.toasterofbread.spmp.api.LoadMediaitemKt$loadMediaItemData$2.invoke(Unknown Source:4)
	at androidx.core.R$dimen.startUndispatchedOrReturn(Unknown Source:4)
	at coil.util.-Contexts.withContext(Unknown Source:71)
	at com.toasterofbread.spmp.api.LoadMediaitemKt.loadMediaItemData(Unknown Source:76)
	at com.toasterofbread.spmp.model.mediaitem.MediaItem$loadGeneralData$2.invokeSuspend(Unknown Source:121)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:100)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(Unknown Source:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:79)
	Suppressed: coil.network.HttpException: [androidx.compose.ui.platform.MotionDurationScaleImpl@5847aec, androidx.compose.runtime.BroadcastFrameClock@5646eb5, StandaloneCoroutine{Cancelling}@a7c794a, AndroidUiDispatcher@d3060bb]

**Comment by powl999** [comment]
I'm on an aosp Android 13 Rom with the Name Pixel os on the xiaomi poco x3 nfc

**Comment by toasterofbread** [comment]
What version of the app are you using? This should have been [fixed](https://github.com/toasterofbread/spmp/issues/70) in v0.1.2.

**Comment by powl999** [comment]
i'm using this version
![Screenshot_20230717-225052](https://github.com/toasterofbread/spmp/assets/72351782/cbedbc4f-c101-430a-98f9-7b31fbd42500)

**Comment by powl999** [comment]
when i go back to the homepage from the erro meassage the app is frozen and only one picture isn't loaded from artist
![Screenshot_20230717-225416_SpMp](https://github.com/toasterofbread/spmp/assets/72351782/6236e509-088b-44ea-9a16-abc5d51dd392)

**Comment by powl999** [comment]
the artist youth neve

**Comment by toasterofbread** [comment]
My bad, this wasn't fixed in v0.1.2, it was fixed right after I made the release. [This](https://github.com/toasterofbread/spmp/actions/runs/5570186505) APK should work.

**Comment by powl999** [comment]
thanks you'r the best

**Comment by toasterofbread** [comment]
No problem, thanks for the report! Let me know if you have any other issues.
