### ISSUE TITLE
[Bug] NullPointerException on radio load while signed in

### ISSUE THREAD

**Issue by powl999** [toasterofbread/spmp#72]
hi me again i just wanted to know if this error code is saying somthing importend i get it when i start playing a song but the app is still working normal

java.lang.NullPointerException
	at com.toasterofbread.spmp.api.radio.GetSongRadioKt$getSongRadio$2.invokeSuspend(Unknown Source:515)
	at com.toasterofbread.spmp.api.radio.GetSongRadioKt$getSongRadio$2.invoke(Unknown Source:8)
	at com.toasterofbread.spmp.api.radio.GetSongRadioKt$getSongRadio$2.invoke(Unknown Source:4)
	at androidx.core.R$dimen.startUndispatchedOrReturn(Unknown Source:4)
	at coil.util.-Contexts.withContext(Unknown Source:71)
	at com.toasterofbread.spmp.api.radio.GetSongRadioKt.getSongRadio(Unknown Source:60)
	at com.toasterofbread.spmp.api.radio.RadioInstance.getInitialSongs-IoAF18A(Unknown Source:144)
	at com.toasterofbread.spmp.api.radio.RadioInstance.access$getInitialSongs-IoAF18A(Unknown Source:0)
	at com.toasterofbread.spmp.api.radio.RadioInstance$loadContinuation$1$1.invokeSuspend(Unknown Source:120)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:100)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(Unknown Source:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:79)
	Suppressed: coil.network.HttpException: [StandaloneCoroutine{Cancelling}@fd6c69b, Dispatchers.IO]

**Comment by toasterofbread** [comment]
Yeah, issues like this are known to happen occasionally. Does it happen every time you try to play a song or just sometimes? If you're logged in to YouTube music, please try to see if it works when you log out.

Basically, what's happening here is that there's something unknown or invalid in the data YouTube sends the app about the song radio, which causes an error. I added a feature recently which allows users to upload the invalid data when parsing the home feed fails so that I can take a look and figure out what's wrong. Once I implement that feature for radio parsing I should be able to fix this issue.

**Comment by powl999** [comment]
only happening when i'm logged in but then every time

**Comment by toasterofbread** [comment]
Ok, that's good. I should be able to fix this issue if you update the app and upload the invalid data once I implement that feature in the next few days,

I'll ping you here then if that's alright?

**Comment by powl999** [comment]
yeah thats ok

**Comment by powl999** [comment]
I know now what doesn't work when I'm logged in and go to a song I can't press the next button there is no waiting queue but in the same scenario if I'm not logged in everything works

**Comment by toasterofbread** [comment]
Yeah, the error message happens when the song radio fail to load, which is why there's no queue.

**Comment by toasterofbread** [comment]
@powl999 I've added the error display which should let you upload the invalid data, it will appear at the bottom of the queue if the loading fails. See if the error still occurs and paste the link to the uploaded data if it does.

**Comment by powl999** [comment]
ok

**Comment by toasterofbread** [comment]
> ok

I forgot to mention, you can get the APK with the feature [here](https://github.com/toasterofbread/spmp/actions/runs/5604232573) once the build finishes. You'll probably have to uninstall the app first since the signatures won't match.

**Comment by powl999** [comment]
the error occurde agin but ther is no erro display on the bottom of the queue
![Screenshot_20230719-234324_SpMp](https://github.com/toasterofbread/spmp/assets/72351782/e0cd8d6a-7200-4bc6-a11d-8bd8828043d4)
java.lang.NullPointerException
	at com.toasterofbread.spmp.api.radio.GetSongRadioKt$getSongRadio$2.invokeSuspend(Unknown Source:522)
	at com.toasterofbread.spmp.api.radio.GetSongRadioKt$getSongRadio$2.invoke(Unknown Source:8)
	at com.toasterofbread.spmp.api.radio.GetSongRadioKt$getSongRadio$2.invoke(Unknown Source:4)
	at androidx.core.R$dimen.startUndispatchedOrReturn(Unknown Source:4)
	at coil.util.-Contexts.withContext(Unknown Source:71)
	at com.toasterofbread.spmp.api.radio.GetSongRadioKt.getSongRadio(Unknown Source:60)
	at com.toasterofbread.spmp.api.radio.RadioInstance.getInitialSongs-IoAF18A(Unknown Source:144)
	at com.toasterofbread.spmp.api.radio.RadioInstance.access$getInitialSongs-IoAF18A(Unknown Source:0)
	at com.toasterofbread.spmp.api.radio.RadioInstance$loadContinuation$1$1.invokeSuspend(Unknown Source:124)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:100)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(Unknown Source:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:79)
	Suppressed: coil.network.HttpException: [StandaloneCoroutine{Cancelling}@4738867, Dispatchers.IO]

**Comment by powl999** [comment]
i just wanted to point out that I can now make an radio with artists and it makes an queue but when i us ean lonley song the error still happens

**Comment by toasterofbread** [comment]
Try this [androidApp-universal-release.zip](https://github.com/toasterofbread/spmp/files/12100461/androidApp-universal-release.zip)

**Comment by powl999** [comment]
ok i will try that

**Comment by powl999** [comment]
paste.ee/p/LZwQ4

there is the link

**Comment by powl999** [comment]
i hope thats helping

**Comment by toasterofbread** [comment]
> i hope thats helping

Perfect, thanks. I should be able to figure out what's wrong from that.

**Comment by powl999** [comment]
nice

**Comment by toasterofbread** [comment]
Fingers crossed, this should fix it:
[androidApp-universal-release.zip](https://github.com/toasterofbread/spmp/files/12100589/androidApp-universal-release.zip)

**Comment by powl999** [comment]
Sorry i Was sleepping i will test it now

**Comment by toasterofbread** [comment]
> Its fixed you are the best

Awesome, thanks for helping with the debugging.

**Comment by toasterofbread** [comment]
Reopening until I commit the fix

**Comment by toasterofbread** [comment]
@Carter0108 You're probably experiencing #292
