### ISSUE TITLE
[Bug] Error after some seconds of the feed loading

### ISSUE THREAD

**Issue by alpha4041** [toasterofbread/spmp#75]
**Describe the bug**
After logging in with my Google account, the feed loads for some seconds then I get this error (see logs). Clicking back doesn't fix it, the app seems like frozen.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install the app
2. Log-in into your account
3. Refresh the feed
4. Error is displayed

**Expected behaviour**
There shouldn't be an error.

**Environment**
- Android 13 QPR3 PixelOS July security patch
- SpMp version 0.1.2
- Accounts: YouTube

**Logs**
```
kotlin.NotImplementedError: it
	at com.toasterofbread.spmp.resources.uilocalisation.AmountStringsKt.parseYoutubeSubscribersString(Unknown Source:95)
	at com.toasterofbread.spmp.api.LoadMediaitemKt$processDefaultResponse$2.invokeSuspend(Unknown Source:929)
	at com.toasterofbread.spmp.api.LoadMediaitemKt$processDefaultResponse$2.invoke(Unknown Source:8)
	at com.toasterofbread.spmp.api.LoadMediaitemKt$processDefaultResponse$2.invoke(Unknown Source:4)
	at androidx.core.R$dimen.startUndispatchedOrReturn(Unknown Source:4)
	at coil.util.-Contexts.withContext(Unknown Source:71)
	at com.toasterofbread.spmp.api.LoadMediaitemKt.processDefaultResponse(Unknown Source:13)
	at com.toasterofbread.spmp.api.LoadMediaitemKt$loadMediaItemData$2.invokeSuspend(Unknown Source:241)
	at com.toasterofbread.spmp.api.LoadMediaitemKt$loadMediaItemData$2.invoke(Unknown Source:8)
	at com.toasterofbread.spmp.api.LoadMediaitemKt$loadMediaItemData$2.invoke(Unknown Source:4)
	at androidx.core.R$dimen.startUndispatchedOrReturn(Unknown Source:4)
	at coil.util.-Contexts.withContext(Unknown Source:71)
	at com.toasterofbread.spmp.api.LoadMediaitemKt.loadMediaItemData(Unknown Source:76)
	at com.toasterofbread.spmp.model.mediaitem.MediaItem$loadGeneralData$2.invokeSuspend(Unknown Source:121)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:100)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(Unknown Source:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:79)
	Suppressed: coil.network.HttpException: [androidx.compose.ui.platform.MotionDurationScaleImpl@1061731, androidx.compose.runtime.BroadcastFrameClock@b8efe16, StandaloneCoroutine{Cancelling}@c5cae4d, AndroidUiDispatcher@c478984]

```

**Comment by powl999** [comment]
I know now what doesn't work when I'm logged in and go to a song I can't press the next button there is no waiting queue but in the same scenario if I'm not logged in everything works
