### ISSUE TITLE
[Bug] Song can't be Put in playlist

### ISSUE THREAD

**Issue by powl999** [toasterofbread/spmp#84]
## Before making a report
Please check existing issues in case your bug has already been reported. Feel free to join the discussion there if you find one, or create a new issue if you don't.

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. While logged in to YouTube
2. Go to '...'
3. Click on '....'
4. Error is displayed 

**Expected behaviour**
A clear description of what you expected to happen.

**Environment**
- OS name and version (ex. Android 13)
- SpMp version (include commit hash if you are using a non-release build)
- Accounts (were you signed in to YouTube, Discord, etc. in the app?)

**Screenshots**
If applicable, add screenshots or recordings to help explain your problem.

**Logs**
Include any relevant error logs or links to uploaded data.

**Comment by powl999** [comment]
While logged in Put an song in exisiting playlist and this error Shows up

java.lang.NullPointerException
	at com.toasterofbread.spmp.model.mediaitem.Playlist.addItem(Unknown Source:28)
	at com.toasterofbread.spmp.model.mediaitem.AccountPlaylist.addItem(Unknown Source:5)
	at com.toasterofbread.spmp.ui.component.mediaitempreview.SongPreviewKt$SongLongPressMenuActions$1$5$1$3$1$1.invokeSuspend(Unknown Source:60)
	at com.toasterofbread.spmp.ui.component.mediaitempreview.SongPreviewKt$SongLongPressMenuActions$1$5$1$3$1$1.invoke(Unknown Source:8)
	at com.toasterofbread.spmp.ui.component.mediaitempreview.SongPreviewKt$SongLongPressMenuActions$1$5$1$3$1$1.invoke(Unknown Source:4)
	at com.toasterofbread.spmp.ui.component.longpressmenu.LongPressMenuData$Actions$1$1$1.invokeSuspend(Unknown Source:63)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:100)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7927)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
	Suppressed: coil.network.HttpException: [StandaloneCoroutine{Cancelling}@e40b9e0, Dispatchers.Main]

**Comment by toasterofbread** [comment]
A few questions: 
- Is the playlist owned by the YouTube account you're signed in with?
- Are there any items already in the playlist?
- Does this happen with other playlists?
- Did you make the playlist in SpMp or on YouTube?

Also, please fill out the issue template in the future and try to include as much relevant information you can, it makes debugging much easier.

**Comment by powl999** [comment]
Yeah thats my Account with my playlist and there Ar 170 Songs in the playlist IT Happen with all playlists the playlist are All made with yt music not with spmp

**Comment by powl999** [comment]
When i make a playlist with the App the Its working and when i upload IT to my YouTube Account thats also working and and after i uploaded IT i can still Put Songs in it

**Comment by toasterofbread** [comment]
The code for playlist editing has completely changed since this was opened. If the issue still exists, the cause will almost certainly be different.

Feel free to open a new issue if you still have problems.
