### ISSUE TITLE
Crash when open app after send it to taskbar. 

### ISSUE THREAD

**Issue by PFARN** [toasterofbread/spmp#96]
When open the app from the multitask it gets paused or well, like ice, idk, so I close it from the multitask and open it again (The music continues reproducing) and it shows the next error.

kotlin.NotImplementedError: PLAYLIST_ACC
	at com.toasterofbread.spmp.resources.uilocalisation.LocalisedYoutubeString$Companion.mediaItemPage(Unknown Source:31)
	at com.toasterofbread.spmp.api.LoadMediaitemKt$processDefaultResponse$2.invokeSuspend(Unknown Source:1178)
	at com.toasterofbread.spmp.api.LoadMediaitemKt$processDefaultResponse$2.invoke(Unknown Source:8)
	at com.toasterofbread.spmp.api.LoadMediaitemKt$processDefaultResponse$2.invoke(Unknown Source:4)
	at androidx.core.R$dimen.startUndispatchedOrReturn(Unknown Source:4)
	at coil.util.-Contexts.withContext(Unknown Source:71)
	at com.toasterofbread.spmp.api.LoadMediaitemKt.processDefaultResponse(Unknown Source:13)
	at com.toasterofbread.spmp.api.LoadMediaitemKt$loadMediaItemData$2.invokeSuspend(Unknown Source:241)
	at com.toasterofbread.spmp.api.LoadMediaitemKt$loadMediaItemData$2.invoke(Unknown Source:8)
	at com.toasterofbread.spmp.api.LoadMediaitemKt$loadMediaItemData$2.invoke(Unknown Source:4)
	at androidx.core.R$dimen.startUndispatchedOrReturn(Unknown Source:4)
	at coil.util.-Contexts.withContext(Unknown Source:71)
	at com.toasterofbread.spmp.api.LoadMediaitemKt.loadMediaItemData(Unknown Source:76)
	at com.toasterofbread.spmp.model.mediaitem.MediaItem$loadGeneralData$2.invokeSuspend(Unknown Source:121)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:100)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(Unknown Source:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:79)
	Suppressed: coil.network.HttpException: [androidx.compose.ui.platform.MotionDurationScaleImpl@af79bb2, androidx.compose.runtime.BroadcastFrameClock@a89b703, StandaloneCoroutine{Cancelling}@1b80680, AndroidUiDispatcher@455f4b9]

**Comment by toasterofbread** [comment]
Should be [fixed](https://github.com/toasterofbread/spmp/commit/c2333882169a7f3c4599bbfe07aa31b8a1c6a55c) now. I added a new section at the bottom of the settings which displays a list of strings that haven't been localised (such as this one). It'd be helpful if you reported any that you find on the [Discord server](https://discord.gg/7RmSgSNVYE).
